### ISSUE TITLE
Link tooltip visible when selecting media

### ISSUE THREAD

**Issue by winterDroid** [GoogleForCreators/web-stories-wp#1969] opened 2020-05-25 05:36 UTC
## Bug Description

When selecting an org icon for a link, the tooltip of the link is still visible in the media gallery.

**Comment by swissspidy** [comment] 2020-05-25 08:42
Could you add some context like a screenshot?

**Comment by winterDroid** [comment] 2020-05-25 23:47
<img width="1679" alt="Screen Shot 2020-05-26 at 9 46 37 am" src="https://user-images.githubusercontent.com/1552225/82848188-d4c53b00-9f35-11ea-9107-43bb80cd101f.png">

There you can see that the link tooltip is still visible.

**Comment by swissspidy** [comment] 2020-05-26 07:46
Possible duplicate of #1082.

**Closed as completed** 2020-05-26 07:51 UTC
Labels: Type: Bug, Status: Duplicate, Group: Links
