### ISSUE TITLE
Search Images/Videos from Web

### ISSUE THREAD

**Issue by mechiragjain** [GoogleForCreators/web-stories-wp#3909] opened 2020-08-14 11:59 UTC
## Feature Description

Many users wanted to add images/videos from Web. So there can be a section named "Search" where one can search for a video or image by typing the keyword. It will make much of the task easy for a user as one can add images or videos from any website who is giving free stock content. 

## Alternatives Considered

Developer can use API of the platforms which are providing open sources images or which allow Google to use their website images.

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment] 2020-08-14 12:03
Hi there,

Could you perhaps elaborate which places you'd want to use to search images on?

Right now we are working on supporting search on [Unsplash](https://unsplash.com/) and [Coverr](https://coverr.co/). Would that suffice for you?

**Comment by mechiragjain** [comment] 2020-08-14 12:10
You can create two tabs under images section. One tab can be for the Wordpress Media and another tab can be for Web Images.

Yes, for now you can proceed with Unsplash and Coverr but in future try to add more platforms like Unsplash so that user will get good options to choose from.

**Comment by swissspidy** [comment] 2020-08-14 12:35
You can see all planned integrations in [this document](https://docs.google.com/document/d/1q8rkYYMKZh3R2eqkpwgGkx6QX0oSXoLYtIO6ml1BFD0/edit#heading=h.xqcejitqohdk).

I am therefore closing this issue in favor of #2354, feel free to follow that ticket for any progress on this matter. Or just wait for the stable release :-)

**Comment by swissspidy** [comment] 2020-08-14 12:36
Duplicate of #2354

**Closed as completed by swissspidy** 2020-08-14 12:36 UTC
Labels: Status: Duplicate, Type: Enhancement, Group: Media
