### ISSUE TITLE
Text padding discrepancy in editor vs preview

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#5436] opened 2020-11-24 21:07 UTC
## Bug Description

Padding shows narrower in editor than in preview on text element. Referenced here: https://github.com/google/web-stories-wp/pull/5434

## Expected Behaviour

There shouldn't be a discrepancy in spacing, the editor and preview should mirror one and other. 

## Steps to Reproduce

This is easiest seen by going to the editor and using the roboto cover text set. See that the "category" text's background looks a little narrow vertically. Now open a preview of that page and see that the vertical space looks fine. 

## Screenshots

**Editor**
![Screen Shot 2020-11-24 at 1 04 30 PM](https://user-images.githubusercontent.com/10720454/100151255-2f484100-2e5e-11eb-8f55-844d5b2a59ce.png)

**Preview**
![Screen Shot 2020-11-24 at 1 04 20 PM](https://user-images.githubusercontent.com/10720454/100151253-2eafaa80-2e5e-11eb-93ff-d528e7e1e2a9.png)

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by miina** [comment] 2022-01-21 13:23
@BrittanyIRL I'm not seeing this issue anymore, looks like it got fixed meanwhile. Closing as such, let me know if you can still reproduce it, then we can reopen.

**Closed as completed by miina** 2022-01-21 13:23 UTC
Labels: Type: Bug, P2, Elements: Text, Group: Workspace
