### ISSUE TITLE
REST API Status Check UX

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#4847] opened 2020-10-08 09:54 UTC
## Feature Description

Related: #4839

This issue is specifically for defining the UX for the status check being worked on in #4790.

If we determine that the REST API is not available, making the editor/dashboard completely unusable, we need to communicate this to the user.

Basically a dialog that says something like this (exact implementation TBD):

```
Warning: Potential Server Misconfiguration

Web Stories for WordPress was unable to freely communicate with the WordPress REST API. This might be caused by interference through another plugin or a firewall.

There might be issues with viewing and editing stories. Contact your server administrator for help and provide the information below:

_______________________________________________
|                                             |
| Reason: HTTP Stauts 403 - Firewall detected |
|                                             |
_______________________________________________

Check out our [documentation] to learn more.

[Try Again] [OK]

```

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by o-fernandez** [comment] 2020-10-08 15:10
Marking as P1 given the high level of frustration this can cause.

**Comment by bmattb** [comment] 2020-10-19 15:56
@o-fernandez to confirm the wording on this after reviewing the error design language from sam.

**Comment by o-fernandez** [comment] 2020-10-20 19:24
Copying from comment on #4918 

@spacedmonkey  following up from our conversation in sprint planning - can you elaborate a bit on what are the reasons why the API post request may fail? Is it always the same reason, or is there a chance for interim issues that would be solved by just retrying?

Will any of these be possible:

- WP Hosting company may be blocking the API requests
- Other WP plugin interference?
- 3P service interference?
- Interim server issue?

Can you let me know and see if it's possible that it's a variety of things? If so, we may want to ask users to reach out to our support forum to try to help them sort it out, until we can provide a better guidance.

If there can be interim failures that resolve themselves, we'd want to minimize the chance of alerting users about this. So, we may want to try a few times prior to erroring out.

**Comment by spacedmonkey** [comment] 2020-10-22 14:27
Reply here https://github.com/google/web-stories-wp/issues/4790#issuecomment-714530710

**Comment by bmattb** [comment] 2020-12-09 14:37
Require clarification from UX on the verbiage and the presentation of the error messaging.

**Comment by o-fernandez** [comment] 2020-12-09 16:43
> Require clarification from UX on the verbiage and the presentation of the error messaging.

Copying and expanding from #4790 

1. Will's suggestion: I think a single check with an exponential backoff retry should suffice. We should make sure to send a GA event when these fail to track volume.

2. When there's consistent failures, let the user know and provide an easy path to open a support request. Ideally a pre-filled support ticket with the right information. 

Suggested message to the user. 

**Error: Unable to save your story.**
We are currently unable to save your story, any changes you make may be lost. This may be due to temporary issues connecting to the WordPress. [Submit a new support topic](https://wordpress.org/support/plugin/web-stories/#new-topic-0) for additional help. 

@samitron7 can you review? 
@swissspidy what is feasible in terms of pre-populating info into a new support topic or providing the right debug information to the user in the error message so they can copy/paste into the support topic? 

@choumx for any additional thoughts.

**Comment by swissspidy** [comment] 2020-12-14 16:38
> what is feasible in terms of pre-populating info into a new support topic or providing the right debug information to the user in the error message so they can copy/paste into the support topic?

It's not possible to do any pre-populating for the WordPress.org support forums. So users would have to manually provide the information manually, as noted in my original suggestion at the top.

**Comment by samitron7** [comment] 2020-12-14 16:45
Use the dialog box [here](https://www.figma.com/file/NHHMwIfxMnz39NxqkrFb7R/Stories---Post-Stable?node-id=2019%3A242702). If the new design hasn't been implemented yet, please use the dialog box using the current styling on the editor.

**Comment by barklund** [comment] 2020-12-15 10:17
@swissspidy, any good suggestion for QA instructions for this one? How can QA reliably reproduce the error and see the message?

**Comment by swissspidy** [comment] 2020-12-15 10:22
Blocking requests to `/web-stories/v1/status-check/` in dev tools could be one option.
Another is to intercept these requests (e.g. using something like https://chrome.google.com/webstore/detail/tweak-mock-api-calls/feahianecghpnipmhphmfgmpdodhcapi (untested)) and return different status codes like 404, 500, or 403.

**Comment by kkalarickal** [comment] 2020-12-15 16:46
Verified on https://stories-qa-wordpress-amp.pantheonsite.io/ by doing the following: 

Test Steps:

1. Setup Chrome/Firefox Dev Tools to block network requests to 
`https://stories-qa-wordpress-amp.pantheonsite.io/index.php?rest_route=%2Fweb-stories%2Fv1%2Fstatus-check%2F&_locale=user`

2. Login to wp-admin and invoke the stories editor in one/all of the following ways:

- Add new story via the menu option on top row or within Stories menu
- Create New story via Stories Dashboard
- Opening an existing story via "Open in Editor" button
- Click "Use Template" to create a templated story

In all cases, the stories editor opens and the following message is displayed:

> Unable to save your story
> 
> We are currently unable to save your story, any changes you make may be lost. This may be due to temporary issues connecting to WordPress. Submit a new support topic for additional help.
> 
> DISMISS

Clicking the "Submit a new support topic" link takes user to "https://wordpress.org/support/plugin/web-stories/#new-topic-0" 

This meets the acceptance criteria for the ticket.

QA Notes:
- Tried to use the tweak-mock-api to intercept the POST request related to status-check. When the status check response was not returned, the error message was NOT displayed.
- Tried to save draft/publish with internet connection switched off. There was a "Failed to save story" popup at the bottom left. It looks like this is a separate check from the status-check in this PR.
- Even with the status check blocked, it was possible to update the Publisher Logo in the Editor Settings. Not sure if the status check should be included in the Editor Settings page since publisher logo update interacts with WP infrastructure and is another way the user can access it without needing to open story editor.

@barklund @csossi

**Comment by spacedmonkey** [comment] 2020-12-16 10:47
@swissspidy Do we need a ticket like this https://github.com/google/web-stories-wp/issues/5644 to also update status check?

**Comment by swissspidy** [comment] 2020-12-16 11:22
This question is better suited for @choumx or @bmattb who hopefully are more aware of the design system plans. See also my recommendation at https://github.com/google/web-stories-wp/pull/5681#issuecomment-745398269 to hold off on merging that one for now.

At some point we need to migrate all dialogs, but that is probably easier to do in one swoop / ticket.

**Comment by o-fernandez** [comment] 2021-01-06 16:50
I did some basic sanity check by opening the editor and disconnecting my internet connection as the editor loaded. Got the right dialog, which is a great start. I'll close this as UAT done since it's already gone through QA.

**Closed as completed by o-fernandez** 2021-01-06 16:50 UTC
Labels: Type: Enhancement, P1, Group: Dashboard, Group: Workspace
