### ISSUE TITLE
Border controls 

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#5455] opened 2020-11-25 16:58 UTC
## Enhancement

1. ~Remove inside and center option for border.~- completed in #5529.
2. Swap out unlock for new version found in the design. (Please ensure this icon is used throughout the editor).

[Figma](https://www.figma.com/file/NHHMwIfxMnz39NxqkrFb7R/Stories---Post-Stable?node-id=1391%3A118)

## Implementation Brief

* Make sure that the lock-buttons are the exact same HTML elements both locked and unlocked, so that keyboard focus stays on the button when pressed (the former is the easiest way to implement the latter).

**Comment by samitron7** [comment] 2020-12-09 23:26
@bmattb Just updated the ticket description and included links to the design.

**Comment by miina** [comment] 2020-12-14 07:59
@barklund / @o-fernandez FYI priority is missing from this issue.

**Comment by barklund** [comment] 2020-12-14 12:05
Item 1. has already been solved in #5529, which is only waiting for UAT, otherwise complete.

Regarding item 2, I cannot prioritize this, as it is mostly a visual change, not a functional one. Deferring to @o-fernandez on priority.

**Comment by barklund** [comment] 2020-12-14 16:44
Oh, part 2 is a duplicate of #5531, which is more specific. So closing this one completely

**Closed as completed by barklund** 2020-12-14 16:44 UTC
Labels: Type: Enhancement, Group: Style Panel
