### ISSUE TITLE
Duplicating a page with animations in it does not duplicate the animations.

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#5502] opened 2020-11-30 20:29 UTC
## Bug Description

When a user duplicates a page with an animation within it, it's expected that the animation and it's settings would also be copied, currently it does not seem to be the case

## Expected Behaviour

Objects that are copied and pasted into the editor should have previously applied animations applied to the new instance

## Steps to Reproduce

1. Create or view a page with an animation applied to an object
2. Copy the element with the animation already applied
3. Paste the element as a new element on this page. Note that the previously applied animations are not transferred to the new instance.

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment] 2020-11-30 20:47
Likely a duplicate of #5424

**Closed as completed** 2020-12-03 21:26 UTC
Labels: P1, Group: Animations, Group: Copy/Paste
