### ISSUE TITLE
Bad metadata in og:image and twitter:image

### ISSUE THREAD

**Issue by cramforce** [GoogleForCreators/web-stories-wp#4678] opened 2020-09-24 17:23 UTC
See

<img width="1023" alt="Screen Shot 2020-09-24 at 10 22 16" src="https://user-images.githubusercontent.com/89679/94178396-e66d0f80-fe4f-11ea-895a-4ad3aaa7687f.png">

Both URLs must be absolute URLs

**Comment by swissspidy** [comment] 2020-09-24 21:57
Closing as duplicate of #4679 since the `wp.stories.google/stories/....` stories are added through a scraper script and had to be fixed manually.

**Closed as completed by swissspidy** 2020-09-24 21:57 UTC
Labels: Type: Bug, Status: Duplicate
