### ISSUE TITLE
SVG Uploads: Disallow as publisher logo or poster image

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#6011] opened 2021-01-22 14:43 UTC
## Bug Description

[Guidelines](https://amp.dev/documentation/components/amp-story/#publisher-logo-src-guidelines) for the poster image and publisher logo are clear:

Provide a raster file, such as .jpg, .png, or .gif. Avoid vector files, such as .svg or .eps.
Avoid animated images, such as animated gifs.

## Expected Behaviour

SVGs should not be allowed as poster image or publisher logo

## Steps to Reproduce

1. Enable SVG experiment
2. Go to Settings
3. Upload a new SVG as publisher logo
4. See that it works

Same happens when you go to the editor and try to add an SVG  as the publisher logo or poster image

## Additional Context

- Plugin Version: 1.3.0
- WordPress Version: 5.6
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by spacedmonkey** [comment] 2021-01-22 15:52
Is this a duplicate of https://github.com/google/web-stories-wp/issues/5124

**Comment by swissspidy** [comment] 2021-01-22 16:21
@spacedmonkey I don't think so:

* This ticket also covers the dashboard
* #5124 says that "These picker should be limited only image mime types that the story editor supports.". But this is incorrect. These pickers don't necessarily support the same mime types as the editor.

**Comment by swissspidy** [comment] 2021-01-28 14:07
#6074 is the PR to QA here.

**Closed as completed** 2021-02-09 11:12 UTC
Labels: Type: Bug, Group: Media, P2, PHP, Group: Dashboard, Group: Settings
