### ISSUE TITLE
Flipped shapes: drop target indicator / on hover line not flipped

### ISSUE THREAD

**Issue by miina** [GoogleForCreators/web-stories-wp#1929] opened 2020-05-21 12:23 UTC
## Bug Description

When a shape (or masked element) is flipped, it's drop target indicator / on hover blue line does not flip together with it.

## Expected Behaviour

The blue line surrounding the element should flip with the element.

## Steps to Reproduce

1. Add a shape, e.g a heart for visibility
2. Flip it vertically.
3. Hover on it
4. See the border not flipped.

## Screenshots
![selection-flip](https://user-images.githubusercontent.com/3294597/82558647-6c114380-9b6e-11ea-9c64-96ac09ce9854.gif)

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by jauyong** [comment] 2020-05-26 13:32
dupe of #1111

**Closed as completed by jauyong** 2020-05-26 13:32 UTC
Labels: Type: Bug, Status: Duplicate, Elements, Group: Selection
