### ISSUE TITLE
Create Custom Templates

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#2866] opened 2020-06-30 19:29 UTC
## Feature Description

Note for Path to stable sheet:
Omar/Sam to draft, Paul to finalize brief [anything that impacts discover/recommends]

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by o-fernandez** [comment] 2020-07-01 20:57
Duplicate of #223

**Closed as completed by o-fernandez** 2020-07-01 20:57 UTC
Labels: Status: Duplicate, Type: Enhancement, Status: Needs More Info, UX Needed
