### ISSUE TITLE
Unwanted Letterboxing

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#905] opened 2020-03-31 17:09 UTC
## Bug Description

Images that span the whole page in the editor are shown with letterboxing in preview. Obviously the user could set the image as a background for this purpose, but it should still match 
Possibly due to the new aspect ratio?

## Expected Behaviour

Editor should match preview

## Steps to Reproduce

1. Add an image to the page
2. Stretch the image to fill the page (do not set as background or use fill)
3. save and preview the story

## Screenshots

Editor:
![image](https://user-images.githubusercontent.com/5874851/78054980-df59be80-7350-11ea-8578-0359c6870ddc.png)

Preview (Notice white padding / letterboxing):
![image](https://user-images.githubusercontent.com/5874851/78055000-e680cc80-7350-11ea-8acd-096779c7df76.png)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by jauyong** [comment] 2020-03-31 17:11
@pbakaus is this a p0 for alpha?

**Comment by pbakaus** [comment] 2020-03-31 19:52
yes. This should be fixed now with the new background resizing behavior though.

**Comment by swissspidy** [comment] 2020-03-31 20:12
@pbakaus The case above is for an image that was manually stretched to more or less fit the page but is **not** actually a background image.

**Comment by pbakaus** [comment] 2020-03-31 20:13
ooooh thanks for the clarification. Not a P0 then, nothing we can really do about that.

**Comment by jauyong** [comment] 2020-04-03 16:44
@dvoytenko @swissspidy it says this was closed via "automation" but I'm not seeing it fixed on staging. Should I reopen this for when we work on P1s?

**Comment by dvoytenko** [comment] 2020-04-03 17:45
Can't repro. Looks good to me. Are you sure you're setting "Fit to device"?

**Comment by jauyong** [comment] 2020-04-03 19:44
This was replicated by several others during our hangout where we all showed our stories.

**Comment by dvoytenko** [comment] 2020-04-03 23:05
Still. Is this b/c the feature is not very discoverable? Or b/c it's broken?

**Comment by pbakaus** [comment] 2020-04-03 23:07
The cases in the hangout where al sadly "working as intended". That is, we all positioned things outside of the background, and these had letterboxing in the output. That's sadly unavoidable at the time being.

**Comment by dvoytenko** [comment] 2020-04-03 23:09
Maybe better default needed? Or auto-background-background for average color/blur?

**Comment by ndev1991** [comment] 2020-04-14 15:35
It's still happening. Step to reproduce. Click image from media gallery. Move it to corner of page and resize it to fit to page manually. Preview mode there are white span on top and bottom.

**Comment by dvoytenko** [comment] 2020-04-14 17:19
/to @pbakaus @samitron7 This can certainly appear as broken to the user. But I believe this is working as intended.

**Comment by ndev1991** [comment] 2020-04-14 17:22
It seems the safe area has wrong size against the full page size. Is this behavior expected?

**Comment by dvoytenko** [comment] 2020-04-14 17:30
Safe area is constructed to be safe against all page sizes (read "most"). So, it will be different from any particular page size you view it on. That's why there are special background/fullbleed rules.

**Comment by pbakaus** [comment] 2020-04-15 05:09
This will be much more obvious, and much easier to fix when we implement the [auto-overflowing safe zone](https://docs.google.com/document/d/1ZF31jSP8BhhLU5Z4Amjfo45UkFUWMEBOTVziY4vursA/edit#heading=h.2d83f6r6hu5x).

**Comment by pbakaus** [comment] 2020-05-02 06:50
This is fixed now that the new auto overflowing safe zone is implemented.

**Closed as completed by pbakaus** 2020-05-02 06:50 UTC
Labels: P1
