### ISSUE TITLE
Dashboard returns "Unable to Load Stories Cannot read property 'publish' of undefined" error

### ISSUE THREAD

**Issue by mickburkesnr** [GoogleForCreators/web-stories-wp#4324] opened 2020-09-03 09:11 UTC
## Bug Description

When clicking on "Stories", then "Dashboard" on WordPress, the dashboard isn't populated with stories that have been created previously. However, clicking on "All Stories" lists them without a problem. Also, within Dashboard, clicking on Templates works and provides you with templates to use. 

Within web inspector console, no errors are provided either.

## Expected Behaviour

Clicking on Dashboard should display the Web Stories dashboard.

## Steps to Reproduce

Click on Stories on the WordPress side bar, then click Dashboard.

## Screenshots
![Screenshot_14](https://user-images.githubusercontent.com/6519882/92095652-d4a6c800-edcd-11ea-9d27-07c2c69ad8ee.png)

## Additional Context

- Plugin Version: Version 1.0.0-beta.2
- Operating System: Windows 10
- Browser: Brave

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by LuckynaSan** [comment] 2020-09-04 17:46
Thank you for submitting your issue. Does this error occur in any other browsers like Chrome or Firefox? Are you able to open up the Web Stories dashboard in an incognito browser? If you'd like to share your [Site Health](https://i.imgur.com/Rtkmsba.png) information we can check if there are any conflicts on the plugin side.

**Comment by mickburkesnr** [comment] 2020-09-08 09:52
So I've tried this on Firefox, Chrome, Edge and Brave and the issue is still the same. 

As for Site Health, here are the things it's picked up:
- Have A Default Theme Available
- The REST API did not behave correctly. - The REST API did not process the context query parameter correctly.

**Comment by swissspidy** [comment] 2020-09-08 10:11
@mickburkesnr Note that for Site health we're generally more intersted in the whole site info data,see this screenshot ("Copy to clipboard"):

<img width="909" alt="Screenshot 2020-09-08 at 12 07 24" src="https://user-images.githubusercontent.com/841956/92463457-208dae80-f1cc-11ea-879e-309c253f130d.png">

That being said, the REST API warnings is key here! This is likely what's causing this issue.

I recommend disabling all plugins to see if that still happens. If not, try activating plugins one by one to find the one causing the issue. If it still happens with all plugins disabled and when using a default theme like Twenty Nineteen, contact your web hosting provider for further assistance.

**Comment by LuckynaSan** [comment] 2020-09-15 19:21
@mickburkesnr Hi there, there is an updated plugin version 1.0.0-rc.1 that is now available. Could you try updating the plugin and let us know if the issue is still occurring?

**Comment by LuckynaSan** [comment] 2020-09-23 15:20
As we have not received a response on this issue, we will close it out. Feel free to post a topic on the [Web Stories Support Forum](https://wordpress.org/support/plugin/web-stories/) if you continue to encounter any issues. Thanks!

**Closed as completed** 2020-09-23 20:50 UTC
Labels: Type: Bug, Type: Support
