### ISSUE TITLE
Scroll bar should be hidden till you hover over the area

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#1845] opened 2020-05-19 01:11 UTC
## Bug Description

Scroll bar should be hidden till you hover over the area. [Figma](https://www.figma.com/file/Cd9iacVknHK62RO4pRwb68/Stories-Editor?node-id=7937%3A13894)

Note: It was originally covered [here](https://github.com/google/web-stories-wp/issues/26#issuecomment-618388872)

## Expected Behaviour

![image.png](https://images.zenhubusercontent.com/5e985a7aea3104e101699670/af23f252-f927-4849-95ae-81df965359ae)

## Screenshots

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment] 2020-05-19 08:47
Duplicate of #1698

**Closed as completed** 2020-05-19 14:26 UTC
Labels: Type: Bug, Status: Duplicate
