### ISSUE TITLE
Text Magic

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#2869] opened 2020-06-30 19:34 UTC
## Feature Description

combo of color, fill style/highlight, line height, frosted glass effect

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by BrittanyIRL** [comment] 2021-07-06 19:31
This is now a duplicate of #7718 which prometheus is already working on.

**Closed as completed by BrittanyIRL** 2021-07-06 19:31 UTC
Labels: Type: Enhancement, Status: Needs More Info, P2, UX Needed, Elements: Text

**Comment by swissspidy** [comment] 2021-07-07 22:43
Hmm I always thought text magic referred to this awesome demo Paul built a while ago: https://codepen.io/pbakaus/pen/gOpZXbW

Which is quite different from #7718 I think

**Comment by BrittanyIRL** [comment] 2021-07-07 22:52
i guess i saw it as iterations, but i don't know. This is just an old ticket and I wanted to get some stuff cleaned up and more current.
