### ISSUE TITLE
TypeError: Cannot read property 'r' of undefined

### ISSUE THREAD

**Issue by Robbi311** [GoogleForCreators/web-stories-wp#4843] opened 2020-10-07 17:32 UTC
TypeError: Cannot read property 'r' of undefined
    in DesignPanel

Something went wrong!
The editor has failed try reloading the page and report the error ...

When selecting two items (form + text) when the error appeared.
It was solved when reloading the page. But if I select again it happens again.

https://paralasiguanas.top/web-stories/datos-interesantes-iguana/

**Comment by swissspidy** [comment] 2020-10-07 22:15
Thanks a lot for your report!

We're tracking this in #4832 and are currently working on a fix in time for our next release.

Duplicate of #4832

**Closed as completed by swissspidy** 2020-10-07 22:15 UTC
Labels: Type: Bug, Status: Duplicate, Group: Style Panel, Group: Patterns
