### ISSUE TITLE
Context menus get cut off in the story view when there are less then a row of stories

### ISSUE THREAD

**Issue by samwhale** [GoogleForCreators/web-stories-wp#6621] opened 2021-03-04 18:56 UTC
## Bug Description

The context menu in the story grid view gets cut off when there are a small amount of stories. This is because the container that is rendering the context menu is hiding the overflow and the menu is too big to fit inside that container.

This popped up in [this PR](https://github.com/google/web-stories-wp/pull/6516#issuecomment-785400403). I decided to add a ticket to fix it separately.

## Expected Behaviour

All items in the context menu should be visible on the screen if the viewport is big enough to show the context menu.

## Steps to Reproduce

1. Go to dashboard
2. Make sure your account only has one row of stories
3. Open a context menu

## Screenshots

![hidey-boi](https://user-images.githubusercontent.com/22185279/109068650-615f7e00-76ad-11eb-8f51-c6bebd2c2031.gif)

Here's some ideas that could fix this problem:

1. make the menu smaller (less items or decrease the padding of the items)
2. Increase the size of the container or add another container that spans the entire viewport height
3. Refactor the context menu into a portal so that it renders outside this part of the tree

## Additional Context

- Plugin Version: 1.5.0-alpha
- WordPress Version: 5.6.2
- Operating System: macOS Big Sur 11.2.1
- Browser: Chrome

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by embarks** [comment] 2021-03-29 18:55
The context menus no longer get cut off. I've attached a video of some testing to show.
https://images.zenhubusercontent.com/235435637/c8dd82ea-88ad-4aa2-b754-eaf3d73175c3/kapture_2021_03_29_at_11_53_37.mp4

Seems the original viewport is now large enough that it does not cut off the context menu. To show an extreme case, I doubled the size of the context menu (by duplicating all the menu items). Now the user can scroll down and see all the times if it opens downwards. But with the normal size, it always opens up and doesn't cut off in either case.

Since this is not reproducible, I'm going to close this ticket.

**Closed as completed** 2021-03-30 22:48 UTC
Labels: Type: Bug, Group: Dashboard, P3
