### ISSUE TITLE
Zoom controls hidden when editing background image

### ISSUE THREAD

**Issue by mariano-formidable** [GoogleForCreators/web-stories-wp#1908] opened 2020-05-20 18:50 UTC
## Bug Description

The zoom controls that appear when double-clicking on a background image are not visible because they're being clipped by the border of the page. 

## Steps to Reproduce

1.) Open up a new story in the editor.
2.) Add an image to the first page and click on "Set as background".
3.) Double-click on the image to reveal the movement/zoom controls.

## Expected Behavior

- I expect to be able to see and use the zoom controls:
![image](https://user-images.githubusercontent.com/40646372/82484281-8ffd5800-9a8e-11ea-96ac-e134d45a79a7.png)

## Actual Behavior
- The zoom controls are _not_ visible.  They're clipped out of view by the page container.

## Screenshots

This is what happens when I double click an image, notice the zoom controls are hidden:
![double-click-image](https://user-images.githubusercontent.com/40646372/82484797-4feaa500-9a8f-11ea-8882-018847ba1af4.gif)

In this image I use the Chrome developer tools to toggle on/off the hidden controls (by toggling `overflow` between `hidden` and `visible`):
![reveal_controls](https://user-images.githubusercontent.com/40646372/82484815-5416c280-9a8f-11ea-8d9e-a3e1bd6f4d61.gif)

## Additional Context

- Plugin Version: Version 1.0.0-alpha (running off staging site)
- Operating System:  Mac OS
- Browser: Chrome

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by barklund** [comment] 2020-05-20 19:34
Duplicate of #1491 and #1873.

**Comment by o-fernandez** [comment] 2020-05-28 22:13
Closing since dupe per prior comment.

**Closed as completed by o-fernandez** 2020-05-28 22:13 UTC
Labels: Type: Bug, P2
