### ISSUE TITLE
Rotated images on top-left offset on canvas are not working and breaking the canvas

### ISSUE THREAD

**Issue by obetomuniz** [GoogleForCreators/web-stories-wp#2101] opened 2020-05-28 20:10 UTC
## Bug Description

Resizing rotated images using bottom-left corner is not working as expected and breaking the canvas. 

The bug behavior is inconsistent. I would recommend a complete review of the resizing/rotating/positioning aspect with images on canvas.

Related to #1011

## Expected Behaviour

Resizing image elements should work anywhere and can't break or affect the canvas.

## Steps to Reproduce

- Add an image element in the workspace canvas
- Rotate the image to 270º, 180º, or 90º
- Move the image in the top-left corner
- Try to use the bottom-left resizing helper 

## Screenshots

![Kapture 2020-05-28 at 16 30 54](https://user-images.githubusercontent.com/1680157/83187057-eeb47880-a103-11ea-8274-c472b08e8448.gif)
![Kapture 2020-05-28 at 16 38 14](https://user-images.githubusercontent.com/1680157/83187065-f07e3c00-a103-11ea-88ef-5668d8c26e96.gif)
![Kapture 2020-05-28 at 16 58 32](https://user-images.githubusercontent.com/1680157/83187853-34257580-a105-11ea-8eb6-9887706159df.gif)
![Kapture 2020-05-28 at 17 03 41](https://user-images.githubusercontent.com/1680157/83188282-d47b9a00-a105-11ea-87ed-46ab0ce4404a.gif)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by miina** [comment] 2020-06-08 08:07
Closing as duplicate of #1011

**Closed as completed by miina** 2020-06-08 08:07 UTC
Labels: Type: Bug
