### ISSUE TITLE
Investigate why controls show percy screenshots.

### ISSUE THREAD

**Issue by spacedmonkey** [GoogleForCreators/web-stories-wp#8685] opened 2021-08-13 11:04 UTC
## Feature Description

Investigate why media controls show percy screenshots. In screenshots, you can clearly see video controls ( like play ) in media library items. 

![2cdb7217cd789213392dde85e36af58290d49f1348288b2ac3b75ea858919041](https://user-images.githubusercontent.com/237508/129348020-72c770c2-b8ea-45dc-bec2-1e41f4a06613.png)

Why is this the case? Why is just happening in screenshots and not browser? Is this happening in linux?

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment] 2021-08-13 12:22
Duplicate of #6422

**Closed as completed by swissspidy** 2021-08-13 12:22 UTC
Labels: Type: Enhancement, Package: E2E Tests
