### ISSUE TITLE
Lasso selection not working at all

### ISSUE THREAD

**Issue by o-fernandez** [GoogleForCreators/web-stories-wp#1593] opened 2020-05-06 15:10 UTC
## Bug Description

See video. Lasso selection doesn't work. I tried using it to select more than one element on the page and it wouldn't work. 

## Expected Behaviour

Lasso selection should select multiple elements on the page that are under the "selection" area. 

## Steps to Reproduce

Add multiple element to a page
Use mouse to select a region (drag mouse over the region while having clicked)

## Screenshots

[lasso selection not working.mov.zip](https://github.com/google/web-stories-wp/files/4587625/lasso.selection.not.working.mov.zip)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment] 2020-05-06 15:29
Duplicate of #1545? That already has a PR by Wassim, #1558.

/ping @wassgha and @miina to confirm

**Comment by miina** [comment] 2020-05-06 15:35
The issue itself doesn't seem like a duplicate (#1545 being about inaccuracy while this issue being about selecting not being possible at all), however, the PR might likely address both issues.

**Comment by swissspidy** [comment] 2020-05-06 15:36
The video shows how 1 element is selected after the lasso instead of 0, that sounds like an inaccuracy. But leaving this one open then for now.

**Comment by jauyong** [comment] 2020-05-13 17:09
this is fixed

**Comment by wassgha** [comment] 2020-05-13 17:09
Closed by #1558

**Closed as completed by jauyong** 2020-05-13 17:09 UTC
Labels: Type: Bug, P0, Group: Selection
