### ISSUE TITLE
Copying and pasting into a text element yields a new text element

### ISSUE THREAD

**Issue by samitron7** [GoogleForCreators/web-stories-wp#2696] opened 2020-06-24 04:00 UTC
Steps to reproduce:
1. Add text element to page
2. Copy text from anywhere and paste into text field
3. A new textfield element will be added to the page with the pasted text

**Comment by swissspidy** [comment] 2020-06-24 06:50
Duplicate of #1953

**Closed as completed by swissspidy** 2020-06-24 06:50 UTC
Labels: Type: Bug, Status: Duplicate, P0, Elements: Text, Group: Copy/Paste
