### ISSUE TITLE
Outside border appears behind text element

### ISSUE THREAD

**Issue by barklund** [GoogleForCreators/web-stories-wp#5370] opened 2020-11-20 17:24 UTC
## Bug Description

If you have an outside border with a border-radius greater than the border width on a text field with a background fill, the border overlaps the element.

However, in the editor, the border is on top, but in the preview, the border is behind the element

## Expected Behaviour

* The border should be on top in both the editor and the preview

## Steps to Reproduce

1. Add a text field
1. Set background to fill
1. Add a 5px black outside border
1. Add a 20px border-radius
1. Click preview
1. Observe that the border is "behind" the text field rather than in front as it is in the editor.

#### In editor
![Screen Shot 2020-11-20 at 12.19.36.png](https://images.zenhubusercontent.com/5e9877d5cc796e8868614c8d/1deb585c-a095-44c3-9b28-1d195bcd9fd6)
#### In preview
![Screen Shot 2020-11-20 at 12.19.44.png](https://images.zenhubusercontent.com/5e9877d5cc796e8868614c8d/eee71186-1c2d-40b1-b5bc-ae8919a03e9f)

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by miina** [comment] 2020-11-23 07:34
@barklund This is a duplicate of #5324, not related to the border itself. Closing as such.

**Closed as completed by miina** 2020-11-23 07:34 UTC
Labels: Type: Bug, P1, Elements: Text, Group: Workspace

**Comment by barklund** [comment] 2020-11-23 22:08
@miina, I wasn't sure if it was related, but if so, please close as long as we check that this is indeed fixed by whatever fix we make to #5324.
