### ISSUE TITLE
Embed Block: Auto-advancing pages might be confusing for users

### ISSUE THREAD

**Issue by cmendla** [GoogleForCreators/web-stories-wp#3561] opened 2020-07-30 14:16 UTC
## Bug Description

If I create a story with the navigation set to auto advance, the story opens at or near the last page. (Because of the rest of the page loading. )

This will be confusing to users new to stories. They will see the last page with no obvious clues that there is navigation available for the story

## Expected Behaviour

The behavior should be that when the page is dom ready, the story is at the first page. 

Also, there should be the ability to display minimal nav tools for the story (Forward, back, restart)

## Steps to Reproduce

- Create a story with advance set to auto
- Embed the story using the wordpress stories plugin in an article with content in addition to the story
- view the article from the front end
- The story will almost certainly not be on the first page by the time the page loads. 

## Screenshots

n/a

## Additional Context

- Plugin Version: Version 1.0.0-beta.1 
- Operating System: Windows 10
- Browser: Chrome  Version 84.0.4147.89 (Official Build) (64-bit)

- WordPress Version 5.4.2

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by ernee** [comment] 2020-07-31 20:20
@cmendla thanks for reaching out!

> If I create a story with the navigation set to auto advance, the story opens at or near the last page. (Because of the rest of the page loading. )

If possible, could you share the URL where the auto-advancing story with the issue is present? 

> Also, there should be the ability to display minimal nav tools for the story (Forward, back, restart)

Thanks for the request! Just to clarify: this is for the story that one would place in a page/ post using the Web Story Embed block?

**Comment by ernee** [comment] 2020-08-12 07:56
@cmendla just a quick update that I've opened the following in the AMP project's repository for your requests: 

https://github.com/ampproject/amphtml/issues/29798
https://github.com/ampproject/amphtml/issues/29799

Feel free to follow them. We'll also keep track of them and provide updates on their progress. Thanks for your suggestions!

**Comment by swissspidy** [comment] 2020-09-24 11:33
I'm closing this for now since this has been reported upstream. We can provide updates here nonetheless.

**Closed as completed by swissspidy** 2020-09-24 11:33 UTC
Labels: Type: Enhancement, AMP Format, AMP Output, Type: Support, Group: Blocks
