### ISSUE TITLE
Wrong color picker placement

### ISSUE THREAD

**Issue by barklund** [GoogleForCreators/web-stories-wp#540] opened 2020-03-11 20:16 UTC
## Bug Description

The color picker opens next to the color input in question when clicked.

However, if the color input is near the bottom of the viewport, the color picker should stay inside the viewport and not be partially hidden.

Furthermore, when the design panel is scrolled due to many options, the color picker does not follow the color input and can suddenly be far away.

## Expected Behaviour

Color picker should follow color input, but stay inside viewport.

## Steps to Reproduce

1.  Make a small viewport
2. Select a text element
3. Collapse the layers panel
4. Scroll the design panel, so text color is at the bottom of the visible panel
5. Click to open the color picker and see that it's partially hidden.
6. Scroll the design panel so text color input moves up and see that the color picker is not moving with it.

## Screenshots

| Initial opening  | Actual view after scroll | Expected view after scroll |
| ------------- | ------------- | ------------- |
| <img width="714" alt="Screen Shot 2020-03-11 at 4 13 02 PM" src="https://user-images.githubusercontent.com/637548/76459828-466bff00-63b3-11ea-9efd-d07f21627c9a.png"> | <img width="714" alt="Screen Shot 2020-03-11 at 4 13 09 PM" src="https://user-images.githubusercontent.com/637548/76459836-48ce5900-63b3-11ea-9923-dccef8718c9c.png"> |   <img width="714" alt="Screen Shot 2020-03-11 at 4 13 18 PM" src="https://user-images.githubusercontent.com/637548/76459834-4835c280-63b3-11ea-90f1-08a3cd7c4e7e.png"> |

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by wassgha** [comment] 2020-04-06 00:58
Same problem with tooltips so I'll take this on

**Comment by Atomicios** [comment] 2020-04-08 21:29
[]()

**Comment by Atomicios** [comment] 2020-04-09 10:02
[]()

**Comment by jauyong** [comment] 2020-04-09 15:29
Hey @wassgha @barklund @miina since this is a duplicate of #961 and that one is in 'Review in Progress' but I see a linked PR here not sure which one I should close?

**Comment by barklund** [comment] 2020-04-09 18:04
This ticket is slightly more explicit in the description and they otherwise 100% overlap, so I'd close #961 as duplicate.

**Closed as completed** 2020-05-11 17:28 UTC
Labels: Group: Editing, P0
