### ISSUE TITLE
Grid view  tooltip lingers after exiting Grid view

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#6723] opened 2021-03-10 21:50 UTC
## Bug Description

Grid view pop up lingers after exiting grid view

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment] 2021-08-12 18:35
@bmattb does this still happen?

**Comment by miina** [comment] 2021-09-23 10:47
It's still happening.

The issue seems to be that the tooltip is being shown on `onFocus` and it looks like that's what's happening once closing the modal -- the button is set to focus again. Not sure what would be a good solution here. 🤔

**Comment by swissspidy** [comment] 2021-09-23 11:35
Setting focus back to the button seems kinda expected from an a11y perspective.

**Comment by miina** [comment] 2021-09-23 11:59
It is expected yep, so not sure if there's a good solution here to focus but not show the tooltip -- we shouldn't remove showing the tooltip when focusing either.

**Comment by swissspidy** [comment] 2021-09-23 13:47
Indeed. In that case I'd say this is working as intended.

**Closed as completed by swissspidy** 2021-09-23 13:47 UTC
Labels: Type: Bug, Good First Issue, Status: Not Implemented, P2, Group: Grid View, Group: Workspace
