### ISSUE TITLE
Saved Styles: Duplicate presets saved

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#4398] opened 2020-09-08 20:14 UTC
## Bug Description

When multiple elements with the exact same style are selected, the "Saved Styles" panel will add multiple identical styles.

## Expected Behaviour

Only one preset should be saved

## Steps to Reproduce

1. Insert two text elements using a preset or the quick shortcut
1. Select both elements
1. Click on "plus" icon in "Saved styles" panel
1. See that two identical styles have been saved

## Screenshots

<img width="948" alt="Screenshot 2020-09-08 at 22 12 33" src="https://user-images.githubusercontent.com/841956/92523380-8e63c580-f220-11ea-999c-53469bfd0eff.png">

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by BrittanyIRL** [comment] 2021-04-05 21:07
This has been resolved elsewhere. Cannot reproduce. Closing.

**Closed as completed by BrittanyIRL** 2021-04-05 21:07 UTC
Labels: Type: Bug, P2, Elements: Text, Group: Saved Styles, Group: Workspace
