### ISSUE TITLE
Provide on/off toggle for autoplay of stories embedded via Story URL

### ISSUE THREAD

**Issue by mxbclang** [GoogleForCreators/web-stories-wp#8004] opened 2021-06-21 20:53 UTC
## Feature Description

Currently, Web Stories that are embedded in pages via any of the Latest Stories or Selected Stories options in Gutenberg (i.e. Grid, List, etc.) do *not* auto-play. However, stories that embedded via Story URL *do* auto-play. Per https://wordpress.org/support/topic/stop-auto-load-when-web-stories-embedded-in-a-page/, users may not want these stories to auto-play as they are not actually being embedded as a single story in a page, but could be laid out on a page using Gutenberg blocks or other tools.

## Alternatives Considered

Disabling auto-play altogether for Story URL embeds, but I do think there are good use cases for it.

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment] 2021-06-22 08:42
Duplicate of #6894

**Closed as completed by swissspidy** 2021-06-22 08:42 UTC
Labels: Status: Duplicate, Type: Enhancement, Group: Blocks
