### ISSUE TITLE
Image selection borders odd/off center when dragging element from edge.

### ISSUE THREAD

**Issue by o-fernandez** [GoogleForCreators/web-stories-wp#1571] opened 2020-05-05 22:27 UTC
## Bug Description

Very weird. I put an image file in the corner of the canvas, most of it out of the canvas zone, in the unsafe zone. When I later dragged the image from the edge the selection border was off centered (see video). 

## Expected Behaviour

The selection "edges"  should continue to be centered. 

## Steps to Reproduce

Place image in canvas edge
Click elsewhere (unselect image)
Drag image from canvas edge into canvas and drop it
Check selection box

## Screenshots

See video
[Weird selection when dragging elements from edge.zip](https://github.com/google/web-stories-wp/files/4583963/Weird.selection.when.dragging.elements.from.edge.zip)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by miina** [comment] 2020-05-28 09:51
Seems like a duplicate of #1787

**Comment by barklund** [comment] 2020-05-28 15:52
Hi @wassgha, have you started working on this?

👍  If you have, please push whatever branch you have (so we can track progress) and move to "in progress".
👎  If not, please un-assign yourself, so someone else can pick this up.

**Comment by jauyong** [comment] 2020-06-01 15:43
@o-fernandez @kmyram 
Async voted resulted in a perfect split. I put the largest estimate for this (8).
![image.png](https://images.zenhubusercontent.com/5e985a7aea3104e101699670/3eb0cd71-5557-49ed-8018-d541bbbaf854)

**Comment by o-fernandez** [comment] 2020-06-01 18:13
@wassgha can you review both this and #1787 and check if: 

- They are duplicates? 
- The point estimate makes sense?

**Comment by wassgha** [comment] 2020-06-04 06:03
Verified duplicate of #1787

**Closed as completed by wassgha** 2020-06-04 06:03 UTC
Labels: Type: Bug, Status: Duplicate, P1, Group: Selection
