### ISSUE TITLE
Valid link treated as invalid

### ISSUE THREAD

**Issue by winterDroid** [GoogleForCreators/web-stories-wp#1966] opened 2020-05-25 05:33 UTC
## Bug Description

Using a valid link (e.g. `https://www.google.com`) still triggers invalid link notification.

## Expected Behaviour

No error message should be returned.

## Steps to Reproduce

1. Insert element
1. Add link
1. Insert `https://www.google.com` as URL
1. See error message saying that the URL is invalid.

## Additional Context

- Plugin Version: `master`
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria

1. An error message is displayed below the input field if the URL is invalid.
1. The fields for the metadata (ie description and brand icon) should only appear if the user enters a valid url.

**Comment by miina** [comment] 2020-06-03 14:24
Quick debugging showed that in case of google.com, the response code is 403 with the following message:
`We're sorry...</h1><p>... but your computer or network may be sending automated queries. To protect our users, we can't process your request right now.`

Tested with some other links and it seems to work fine generally.

Q: What's the expected behavior in case of the forbidden error message as in the case of Google? Should we display something else in the snackbar instead of just "Invalid link"? Thoughts?

cc @o-fernandez @swissspidy

**Comment by swissspidy** [comment] 2020-06-03 14:43
As a user I don't expect **any** message in that case. Even If I add a URL like `https://thiswebsitedoesnotexist.org` on purpose.

Especially since the URL is only fetched to get metadata for a page (i.e. title, image, description).

If I add an inexistent URL, the metadata will be simply empty.

The only place where I expect an error message is if I pass a malformed URL or an empty string.

**Comment by o-fernandez** [comment] 2020-06-03 19:34
Yeah, I wonder if we just have basic validation logic instead of actually making requests/testing the URLs. Is there a simple library/rule set we can use to check for valid URL structure?

**Comment by swissspidy** [comment] 2020-06-03 19:51
@o-fernandez Note that we aren‘t requesting the URLs to see if they‘re valid. We make requests to retrieve page metadata like the title. Some basic validation logic is done in that process.

**Comment by o-fernandez** [comment] 2020-06-03 19:52
@swissspidy that's great. Then how come google.com was showing as invalid, per the original bug report? Or did I misunderstand the bug?

**Comment by swissspidy** [comment] 2020-06-03 19:58
Because the site blocks such automated requests like ours. We just need to catch such cases better / not treat them as errors.

**Comment by o-fernandez** [comment] 2020-06-03 20:14
Got it, yes, my bad in how I phrased the prior comment. Agree that we should not show the user "invalid" link in such cases.

**Comment by wassgha** [comment] 2020-06-04 05:52
Seems like a PHP-side solution is needed here. I'd see if we're caching the requests and look more into the user agents used etc. Nevertheless, I think we should reassign and bring down from P1 to P2.

**Comment by spacedmonkey** [comment] 2020-06-05 12:51
Moving discussion for the PR, I think that if the URL doesn't return a 200 status, it should return an error. Other states should maybe just return an empty title, description and should not cache.

**Comment by swissspidy** [comment] 2020-06-12 09:39
> if the URL doesn't return a 200 status, it should return an error. Other states should maybe just return an empty title, description and should not cache.

So what is it, error or empty data on other states?

The case reported here is that a 403 status should not return an error, which is what #2254 handles.

**Comment by swissspidy** [comment] 2020-06-16 13:37
See #2254 for instructions.

**Comment by csossi** [comment] 2020-06-17 02:25
When I enter an invalid URL, I see the warning message:
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/b079a90a-1969-4452-b7b7-108a88f8ea3c)

If I navigate away from element and REselect it, the message is no longer there:
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/928d7002-9366-47e5-b012-da2418595f2f)

Should this message be maintained? Please advise if ok=as-is

**Comment by swissspidy** [comment] 2020-06-19 08:29
@csossi Can you test again? The error message should now persist.

**Comment by csossi** [comment] 2020-06-19 14:53
Not seeing an error message at all now:
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/36da9ca4-13e9-44ba-a6c4-7ea0afbadfea)

**Comment by swissspidy** [comment] 2020-06-22 08:43
@csossi Well, that's a different URL 🙂 I've made the URL test a bit more restrictive now, PTAL. Try with something simple like just `http://`.

I'll create a follow-up ticket about making the check more robust for other cases. For now, the focus is on persistence and appearance of the error message.

**Comment by swissspidy** [comment] 2020-06-22 09:54
@csossi Another thing to verify: the fields for link description & icon should not be displayed in case of an error.

**Comment by csossi** [comment] 2020-06-22 19:31
Verified in QA:
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/66160102-9692-498d-bdd1-169c08e8b739)

**Comment by samitron7** [comment] 2020-06-29 15:58
I'm able to enter in a garbage url and not getting a error message

![Screen Shot 2020-06-29 at 8.57.21 AM.png](https://images.zenhubusercontent.com/5e9dc6e34754fda9ccd26e86/c91892b0-dab3-4e22-86ed-8873ce9e927f)

**Closed as completed** 2020-06-29 19:01 UTC
Labels: Type: Bug, P2, Group: Links
