### ISSUE TITLE
Flaky Karma test: should apply formatting correctly for multi-style text field

### ISSUE THREAD

**Issue by miina** [GoogleForCreators/web-stories-wp#4396] opened 2020-09-08 17:19 UTC
The test for `CUJ: Creator Can Style Text: Apply B, Apply U, Apply I, Set text color, Set kerning` and `should apply formatting correctly for multi-style text field` is sometimes failing with the following error message:
<img width="1003" alt="Screenshot 2020-09-08 at 19 50 29" src="https://user-images.githubusercontent.com/3294597/92507993-273a1700-f208-11ea-939f-03ac8f09fc1f.png">

**Comment by swissspidy** [comment] 2020-09-08 17:20
cc @barklund

**Comment by barklund** [comment] 2020-09-10 17:38
@swissspidy, why was this moved to review? Mouseslip?

**Comment by swissspidy** [comment] 2020-09-10 17:47
@barklund yep, mouseslip!

**Comment by bmattb** [comment] 2020-09-23 18:06
duplicate of #3465 closing.

**Closed as completed by bmattb** 2020-09-23 18:06 UTC
Labels: Status: Duplicate, Type: Enhancement, Type: Infrastructure, Elements: Text
