### ISSUE TITLE
Published story is not responsive

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#4692] opened 2020-09-25 15:13 UTC
## Bug Description

Reported to me by Paul:

> my friend kristi has embedded a story on her site: https://www.mysanfranciscokitchen.com/the-best-vegan-caramel-sauce/

Reviewing the story I on mobile I am seeing what appears to be a responsive story, however would require confirmation

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment] 2020-09-25 15:18
Looks like a duplicate of #3581

**Comment by swissspidy** [comment] 2020-09-25 15:20
You'll see how the story extends its container on mobile:

<img width="476" alt="Screenshot 2020-09-25 at 17 19 13" src="https://user-images.githubusercontent.com/841956/94284845-3da7d880-ff53-11ea-9eec-a841b4a04af2.png">

Note that we're already working on this — #3581 is currently _in progress_ / code review

**Closed as completed by swissspidy** 2020-09-25 15:20 UTC
Labels: Type: Bug, Status: Duplicate, Group: Blocks
