### ISSUE TITLE
1 Click CTA on Textbox Not showing on FE

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#1043] opened 2020-04-03 19:30 UTC
## Bug Description

After adding a 1 click CTA to the last page and saving the story, it doesn't show up in preview. 

my example story: https://stories-new-wordpress-amp.pantheonsite.io/wp-admin/post.php?post=733&action=edit

## Expected Behaviour

Everything you add in the editor should show up on the front end!

## Screenshots

See learn more at the bottom in the editor:
![image](https://user-images.githubusercontent.com/5874851/78397880-08cc5180-75c0-11ea-90ff-78805143544d.png)

See that learn more is missing on when previewing:
![image](https://user-images.githubusercontent.com/5874851/78397932-25688980-75c0-11ea-9e1b-75dbf5cf6ff3.png)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by miina** [comment] 2020-04-03 19:40
@jauyong Might be a duplicate of #1000. 

See also https://github.com/google/web-stories-wp/issues/1000#issuecomment-608491776

**Comment by swissspidy** [comment] 2020-04-04 10:32
Duplicate of #1000

**Closed as completed by swissspidy** 2020-04-04 10:32 UTC
Labels: Status: Duplicate, P0
