### ISSUE TITLE
Default Page Duration input

### ISSUE THREAD

**Issue by spacedmonkey** [GoogleForCreators/web-stories-wp#2079] opened 2020-05-28 11:47 UTC
## Bug Description

Default Page Duration input allows use to enter value higher than max 20. 

## Expected Behaviour

This input should be `type="number"` and have a min and max value. If a user enters a value higher than 20, then it should be reset back to 20. 

## Steps to Reproduce

See video.

## Screenshots

https://youtu.be/-FvpPH2D0WQ

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by barklund** [comment] 2020-05-28 18:41
This is kind-of-but-not-really a duplicate of #1905. Ping @o-fernandez for input on this one.

**Comment by o-fernandez** [comment] 2020-05-28 18:57
Let's close as dupe of #1549 and added [min/max values to the doc](https://docs.google.com/spreadsheets/d/1hdru-_p4Yk-VFQ1rEFGYHHI2A7eNZkxLA33-LblG8sE/edit#gid=0)

**Closed as completed by o-fernandez** 2020-05-28 18:57 UTC
Labels: Type: Bug, Status: Duplicate, Group: Document Panel
