### ISSUE TITLE
Prepublish Checklist

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#1241] opened 2020-04-15 19:38 UTC
## Feature Description

As an author, I'd like a prepublish checklist to ensure my published stories are in an optimal state.

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by jauyong** [comment] 2020-04-15 19:39
@samitron7 @pbakaus 
Can you let me know when you've written details for this?
And can you also help prioritize this please.

**Comment by swissspidy** [comment] 2020-04-21 15:00
@jauyong Duplicate of #78?

**Closed as completed** 2020-04-21 15:25 UTC
Labels: Status: Duplicate
