### ISSUE TITLE
Adding text presets crashes editor

### ISSUE THREAD

**Issue by csossi** [GoogleForCreators/web-stories-wp#1990] opened 2020-05-26 14:37 UTC
## Bug Description

Opted to add text by clicking the "+" symbol. On doing so, display turned blank

## Expected Behaviour

Text field should appear on canvas

## Steps to Reproduce

- create/open story
- select page (if applicable)
- select "+" symbol beside "T"

## Screenshots

Selected + Symbol:
![image](https://user-images.githubusercontent.com/16945664/82913729-abf47400-9f3c-11ea-9e3a-59724cbdeb77.png)
On selection, page turned blank:
![image](https://user-images.githubusercontent.com/16945664/82913828-c595bb80-9f3c-11ea-96a3-4e11b7161065.png)

## Additional Context

- Plugin Version:
- Operating System: Win10
- Browser: Chrome

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment] 2020-05-26 14:42
Happening when user selects "T" and tries to add text that way as well

**Comment by swissspidy** [comment] 2020-05-26 15:33
@csossi I cannot reproduce this on master. Since you're on the QA site, please note that you are currently testing a specific PR there:

<img width="632" alt="Screenshot 2020-05-26 at 17 29 51" src="https://user-images.githubusercontent.com/841956/82919603-897f4c80-9f76-11ea-8710-d1c82aca2eaf.png">

If you find such an issue when testing a specific PR there are a few possibilities:

1. It was an issue that has since been fixed on master, but the PR has not been updated -> ask PR author to rebase PR.
1. It is a specific issue with the PR -> leave review on PR
1. It is an issue unrelated to the PR -> open a new issue

EDIT: apparently it's been confirmed to happen on master too

**Comment by jauyong** [comment] 2020-05-27 13:46
This is not crashing for me, not sure if it's a windows specific issue...

**Comment by swissspidy** [comment] 2020-05-27 18:49
Apparently Marcin was able to reproduce, hence my resolved comment

**Comment by csossi** [comment] 2020-06-03 17:20
Verified in QA

**Closed as completed** 2020-06-12 14:38 UTC
Labels: Type: Bug, Group: Text Sets
