### ISSUE TITLE
Browser selecting smaller image sizes

### ISSUE THREAD

**Issue by LuckynaSan** [GoogleForCreators/web-stories-wp#6428] opened 2021-02-18 16:15 UTC
## Bug Description
Safari and Chrome browsers are picking the small version of an image from `srcset` when there are larger sizes [in the source code](https://jumpshare.com/v/Xhu7Yn8kayFJpwU1G04e).

## Expected Behaviour

The browser should display the larger image in the list. 

## Steps to Reproduce

Open user's story in Chrome/Safari and notice the [lower-resolution image](https://www.ridesharingdriver.com/wp-content/uploads/2021/01/ride-types-uber-147x300.jpg) displaying. 

Notice issue does not occur in MS Edge or Firefox. 

## Screenshots
Chrome:
Screen Shot 2021-02-18 at 10.45.58 AM
![image](https://user-images.githubusercontent.com/66372350/108385637-dcbabe80-71d9-11eb-9318-569eeea4fa97.png)

Edge: 
![image](https://user-images.githubusercontent.com/66372350/108385565-cc0a4880-71d9-11eb-8da6-916bdef9abd0.png)

## Additional Context

Related topic: https://wordpress.org/support/topic/troubleshooting-image-quality-some-images-unexpectedly-low-res/ 

- Plugin Version:
- WordPress Version: 
- Operating System:
- Browser: Chrome, Safari

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment] 2021-02-18 17:30
I'm not so sure this is a bug per se, as the browser does work as expected, processing the `srcset` attribute.

The issue seems to be that the image is animated and transformed because of these animations, appearing larger than what's in the source, causing the browse to ignore the original size.

@littlemilkstudio @barklund Perhaps this is something one of you could confirm?

The image in question is on page 2 of this story: https://www.ridesharingdriver.com/web-stories/uber-ride-types/

**Comment by swissspidy** [comment] 2021-02-18 17:36
OK seconds after I posted this they updated the story to remove animations and the issue is gone 🙃

**Comment by swissspidy** [comment] 2021-07-06 15:46
Closing in favor of #7500 

This should be fixed in 1.9

**Closed as completed by swissspidy** 2021-07-06 15:46 UTC
Labels: Type: Bug, Status: Duplicate, Elements: Image, Group: Animations, AMP Output, Type: Support
