### ISSUE TITLE
Page Layouts : Keyboard navigation keys don't work the same as with other layouts

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#5904] opened 2021-01-12 20:18 UTC
## Bug Description

reported by : @barklund 

Tabbing and arrow keys should work similarly for page layouts as they do for the image layouts used in the other library tabs. Tab should move into and out of the list of page layouts and arrow keys should move between the layouts.

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by BrittanyIRL** [comment] 2021-01-13 02:47
Duplicate of #5876

**Closed as completed by BrittanyIRL** 2021-01-13 02:47 UTC
Labels: Type: Bug, Status: Duplicate, Accessibility, Group: Page Templates

**Comment by swissspidy** [comment] 2021-01-13 10:26
@BrittanyIRL Pro tip: you can use `Duplicate of #123`, see https://docs.github.com/en/free-pro-team@latest/github/managing-your-work-on-github/about-duplicate-issues-and-pull-requests
