### ISSUE TITLE
Global Settings Page

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#570] opened 2020-03-13 14:39 UTC
## Feature Description

**[Design - See P0 section](https://www.figma.com/file/Cd9iacVknHK62RO4pRwb68/Stories-Editor?node-id=6095%3A1)**
**[Publisher Logo UX](https://www.figma.com/file/Cd9iacVknHK62RO4pRwb68/Stories-Editor?node-id=5837%3A4)**

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria

1. The user is able to add their Google Analytics ID
2. The user is able to upload a publisher logo
3. If sitekit is in use, direct users with appropriate information on the settings page

**Comment by miina** [comment] 2020-04-13 06:58
Related #1168

**Comment by BrittanyIRL** [comment] 2020-05-04 23:37
Notes from duplicate ticket: 

Add in the "Stories Global Settings" page.

Visible when "Editor Settings" is clicked in left nav.
Has the ability to return back to dashboard view (last view or back to my stories?)
Has the ability to enter Google Analytics Tracking ID
Needs an API
Has the ability to upload logos for stories as Publisher Logos
Needs an API

![Stories Global Settings](https://user-images.githubusercontent.com/10720454/81023522-87b5e380-8e25-11ea-88b9-b8da59597937.png)

**Comment by jauyong** [comment] 2020-05-13 17:16
Moving this to icebox, not a priority for beta

**Comment by jauyong** [comment] 2020-05-13 17:23
@jauyong to create a separate ticket for AC2 and add:
Add Helper Text to Publisher Logo in Doc Panel Explaining. Assign this ticket to Sam.

AC1&3 will be pushed to stable release.

**Comment by jauyong** [comment] 2020-05-13 18:00
Removed this AC and created #1763
2. The user is able to upload a publisher logo

**Comment by o-fernandez** [comment] 2020-07-13 15:52
Closing as dupe of #2747

**Closed as completed by o-fernandez** 2020-07-13 15:52 UTC
Labels: Status: Duplicate, Type: Enhancement, Group: Dashboard, Group: Settings
