### ISSUE TITLE
Infrastructure: integration tests

### ISSUE THREAD

**Issue by dvoytenko** [GoogleForCreators/web-stories-wp#1170] opened 2020-04-13 16:21 UTC
We need to improve testing infrastructure, and in particular integration tests. For this task we only want to test stories editor independently and as such:

1. We want to look at the editor as a whole.
2. We want to run in a real browser environment.
3. WP dependencies can be mocked out. Specifically it means that media and fonts APIs can be mocked out, unless we find an easy and stable way to run it locally or on Travis.
4. Load/save story APIs can be simply mocked up by feeding JSON in and out.
5. Anything related to media uploads is mandatory to have tests for

The test itself could be executed this way:

1. As far testing is concerned, we have an option is to either construct and load the complete editor, or at least a bigger section. The preference is for the whole editor.
2. The driving script has to read naturally: "(a) add the element; (b) check element selected; (c) go to the design panel; (d) change font size; (e) check the font size is reflected and the height of the text block is expanded".
3. Using the true mouse/keyboard events could be beneficial. As such, we can settle on a single predefined screen size.

Note:
Consider Pasting to upload #761 as a first candidate
@spacedmonkey needs to review this before marking as done to make sure anything media related has proper test coverage

**Comment by swissspidy** [comment] 2020-04-15 16:15
Related: #374. The storybook could be navigated on using Puppeteer

---

Since visual regression tests were mentioned:
In my experience [BackstopJS](https://github.com/garris/BackstopJS) is too heavy for that, even when tweaking thresholds etc. [`jest-image-snapshot`](https://github.com/americanexpress/jest-image-snapshot) could perhaps be a lighter alternative as it works on individual React components and not the whole app. Bonus: via [StoryShots](https://github.com/storybookjs/storybook/tree/master/addons/storyshots#configure-storyshots-for-image-snapshots) it has a seamless integration with storybook

**Comment by dvoytenko** [comment] 2020-04-15 23:00
AMP uses http://percy.io/ for visual testing.

**Comment by swissspidy** [comment] 2020-04-23 12:00
See #1317 for how we can run E2E tests on Firefox.
See #1318 for an example visual regression test for individual components.

**Comment by swissspidy** [comment] 2020-04-23 12:03
Looking at #1316, which is related to media, could we test `useCanvasSelectionCopyPaste` by constructing our own clipboard data event?

**Comment by swissspidy** [comment] 2020-04-23 16:39
Some initial notes from our call:

* Need to mock API and media related parts to make editor work standalone (#374)
* There's a current Puppeteer setup (which supports Chromium - and now also Firefox! #1317)
 * Alternative solutions are Selenium WebDriver and Cypress
 * Cypress does not support native events
 * Puppeteer does not support other browsers at the moment
 * Extremely good browser coverage is not too important for now. Even working tests in one browsers would be great
 * Switching from one tool to another would be difficult
* We want to focus on testing the most crucial areas first. This includes things like:
  * Drop Targets
  * Text selection
  * Integration between design panel and canvas (e.g. change font size -> change reflected on canvas)
  * Copy / Paste
  * Media upload
* Ideally E2E tests are fairly easy to write and read
  * Current Puppeteer setup uses Jest to write assertions
  * https://codecept.io/basics/ is an alternative way with BDD-style syntax (Gherkin)
  * https://github.com/testing-library/pptr-testing-library would allow using same test syntax as in unit tests
* New PRs should include proper tests
  * New code coverage report helps encouraging this
  * Decide on a case-by-case basis whether this means more unit / integration tests / E2E tests
  * We could add labels to PRs to clearly mark them as "needs tests"
  * Reduce back-and-forth between development & QA by having proper tests documenting the intention and validating the feature/fix.
  * need to properly document the whole test process
  * writing these kinds tests should become more natural / a habit
* visual regression tests
 * visual regression tests for single components are doable (see #1318 as PoC)
 * need to be done on the same platform, otherwise there can quickly be mismatches
 * on a case-by-case basis. don't always make sense
 * one benefit of Percy is less overhead for us, as the platform deals with most of the things
* @merapi offered to tackle some critical test areas (as mentioned above) with Puppeteer
  * if we can test those with Puppeteer, it's an indicator that this tool suffices for us
  * if it doesn't work, we might need to switch tools
* @cvolzke4 offered to kickstart a design doc for this

Please leave a comment if I forgot anything.

**Comment by dvoytenko** [comment] 2020-04-23 22:08
@swissspidy Thanks, this looks good! Also, someone (you?) mentioned that we could use the existing storybooks for a low-hanging fruit e2e tests?

**Comment by cvolzke4** [comment] 2020-04-24 09:41
I've created a draft design go/greendoc so that we can comment on the different approaches in a shared doc format:
go/storytime-e2e-ideas

**Comment by spacedmonkey** [comment] 2020-04-27 13:10
I created a related ticket on areas of the media component that need some extra testing.  #1346

**Comment by swissspidy** [comment] 2020-06-02 12:45
Closing this for now as the foundation for this has been built.

**Closed as completed by swissspidy** 2020-06-02 12:45 UTC
Labels: P0
