### ISSUE TITLE
Page attachment into the story like swipe up 

### ISSUE THREAD

**Issue by uditrathod9** [GoogleForCreators/web-stories-wp#3895] opened 2020-08-14 04:32 UTC
## Feature Description

Allow user to link a webpage along with the stories pages, so people can learn more about the thing they are looking for.

**Comment by swissspidy** [comment] 2020-08-14 08:35
Thanks for your report! We're already working on page attachment support as you'll quickly find when searching for existing issues. Please follow #254 for updates.

**Comment by swissspidy** [comment] 2020-08-14 08:35
Duplicate of #254

**Closed as completed by swissspidy** 2020-08-14 08:35 UTC
Labels: Status: Duplicate, Type: Enhancement, Group: Page Attachment
