### ISSUE TITLE
Arrow keys in edit mode move the outer element, not the mask

### ISSUE THREAD

**Issue by pbakaus** [GoogleForCreators/web-stories-wp#1426] opened 2020-05-01 03:53 UTC
## Bug Description

Arrow keys in edit mode move the outer element, not the mask

## Expected Behaviour

Arrow keys in edit mode should reposition the inner image/video, not the outer element.

## Screenshots

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by wassgha** [comment] 2020-06-04 05:38
Duplicate of #1426 , already has PR #2108

**Closed as completed by wassgha** 2020-06-04 05:38 UTC
Labels: Type: Bug, P1, Elements, Group: Selection
