### ISSUE TITLE
Paste text from elsewhere destroys existing styling in the text box

### ISSUE THREAD

**Issue by o-fernandez** [GoogleForCreators/web-stories-wp#4593] opened 2020-09-21 15:01 UTC
Scenario: 

- User has a text box in the canvas with nice styling
- User "paste and match styles" or "cmd+shift+v" text from elsewhere

Expectation: text box styling is applied to the newly pasted text. 

Current behavior: Styling is destroyed.

**Comment by barklund** [comment] 2020-09-21 16:01
Duplicate of #1605

**Closed as completed by barklund** 2020-09-21 16:01 UTC
Labels: Status: Duplicate, P0, Elements: Text, Group: Copy/Paste
