### ISSUE TITLE
Set Min and Max values input values

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#1905] opened 2020-05-20 17:25 UTC
Current spec: [Min/max values](https://docs.google.com/spreadsheets/d/1hdru-_p4Yk-VFQ1rEFGYHHI2A7eNZkxLA33-LblG8sE/edit#gid=0)

These values are rough guesses based on what seems reasonable, but subject to revision as we learn more from users.

**Comment by obetomuniz** [comment] 2020-05-27 19:03
#1549 Duplicate @jauyong @o-fernandez ?

**Comment by o-fernandez** [comment] 2020-05-27 21:01
Closed as dupe of #1549

**Closed as completed** 2020-05-27 21:00 UTC
Labels: Status: Duplicate, Status: Needs More Info, P1, UX Needed
