### ISSUE TITLE
Perfect highlight formula to produce exact bounding box

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#835] opened 2020-03-27 14:23 UTC
## Bug Description

Perfect highlight formula to produce exact bounding box

Followup to #684 
https://github.com/google/web-stories-wp/pull/684#issuecomment-604789334

## Screenshots

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## QA Instructions

With different combinations of text content and font family/size, you shouldn't be able to end up in a state when the frame (blue box) is not matched to text contents inside the editor (on canvas) and should look the same (especially newlines placement) in the final story (preview).

NOTE: There are some know issues (Chrome bug[?]) so please DM @merapi to verify if it's a valid one.

**Comment by jauyong** [comment] 2020-05-13 17:43
Reviewed May 13, keeping in icebox.

**Comment by o-fernandez** [comment] 2020-05-19 23:07
This is marked as a P1, question whether this is still (1) important and (2) we have a solution designed for it?  @barklund

**Comment by barklund** [comment] 2020-05-20 00:10
I don't have an idea for a solution, but nor have I looked for one since this.

However we actually have [this feature request](https://docs.google.com/presentation/d/1ZiZWrmLiX40rt3n_1LMSGJxYWI-xsWFsS9bkzdbRIV8/edit?ts=5ec37b15#slide=id.g7830109f71_0_105) which is more urgent and related to this issue (not the same one, but involves some of the same calculations), so solving that might involve finding a solution for this one too.

**Comment by o-fernandez** [comment] 2020-05-20 20:29
Sounds good. I'd say this seems important for Stable, not for Beta. @samitron7 please chime in if you think it's crucial for Beta.

**Comment by bmattb** [comment] 2020-07-27 15:43
connected PR is ready for review & merge.

**Comment by bmattb** [comment] 2020-07-27 15:44
@merapi  to add edge cases that are not covered here

**Comment by samitron7** [comment] 2020-08-11 06:31
@merapi Do any of these edge cases require u input?

**Comment by merapi** [comment] 2020-08-11 10:11
I added the info about edge cases/potential bugs to the description, if anybody finds one then we will analyze it on a case-by-case basis (and see if they are fixable).

**Comment by samitron7** [comment] 2020-08-14 06:07
That are the steps to reproduce?

**Closed as completed** 2020-09-09 15:26 UTC
Labels: P1, Elements: Text
