### ISSUE TITLE
Auto-extracted poster image is named just "image.jpeg"

### ISSUE THREAD

**Issue by westonruter** [GoogleForCreators/web-stories-wp#4707] opened 2020-09-27 05:02 UTC
## Bug Description

I uploaded a video with the filename `PXL_20200907_180100-trimmed.mp4`. Upon adding it to a story page and previewing the story, I saw that the `poster` image of the video was set to be simply `image.jpeg`:

```html
<amp-video autoplay="autoplay" poster="https://wordpressdev.lndo.site/content/uploads/2020/09/image.jpeg" artwork="https://wordpressdev.lndo.site/content/uploads/2020/09/image.jpeg" layout="fill" loop="loop" id="el-b8f30411-37f5-4e4e-ace6-8b2666470bd2-media">
    <source type="video/mp4" src="https://wordpressdev.lndo.site/content/uploads/2020/09/PXL_20200907_180100-trimmed.mp4"></source>
</amp-video>
```

I then uploaded a second video and added it to another story page, and the resulting markup for the video showed that its `poster` became `image-1.jpeg`:

```html
<amp-video autoplay="autoplay" title="PXL_20200908_112624" alt="PXL_20200908_112624" layout="fill" id="el-a53fd0ec-3173-42e7-a36c-6075a7eeb970-media">
    <source type="video/mp4" src="https://wordpressdev.lndo.site/content/uploads/2020/09/PXL_20200908_112624.mp4"></source>
</amp-video>
```

This is not ideal. I was expecting the first to be named `PXL_20200907_180100-trimmed.jpeg` and the second `PXL_20200908_112624.jpeg`, not `image.jpeg` and `image-1.jpeg` respectively.

## Expected Behaviour

The poster image filename should ideally use the basename of the video it was generated from.

## Steps to Reproduce

Upload a video and add it to a story. View the story's markup and see the filename of the video `poster`.

## Additional Context

- Plugin Version: 1.1.0-alpha
- Operating System: MacOS
- Browser: Chrome

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment] 2020-09-27 08:55
Duplicate of #3228

**Closed as completed by swissspidy** 2020-09-27 08:55 UTC
Labels: Type: Bug
