### ISSUE TITLE
Video corner radius issue in mobile device

### ISSUE THREAD

**Issue by LuckynaSan** [GoogleForCreators/web-stories-wp#7359] opened 2021-05-03 17:51 UTC
## Bug Description

Videos with a corner radius applied do not render correctly when viewing it on a mobile device.

## Expected Behaviour

Videos with corner radius should display correctly viewing them on mobile devices. 

## Steps to Reproduce

1. Add video to a story
2. Apply a corner radius
3. View the story on any of these mobile devices: iPhone 12 or iPhone 11, Chrome or Safari

## Screenshots
Editor - corner radius set to 50
<img width="910" alt="Screen Shot 2021-05-03 at 1 48 24 PM" src="https://user-images.githubusercontent.com/66372350/116912525-54638b80-ac16-11eb-8287-b246d9df6361.png">

Preview on the mobile devices
<img width="687" alt="Screen Shot 2021-05-03 at 1 44 59 PM" src="https://user-images.githubusercontent.com/66372350/116912566-634a3e00-ac16-11eb-902a-bda04d44141d.png">

## Additional Context
Tested Android device in Browserstack and no issues found.
<img width="615" alt="Screen Shot 2021-05-03 at 1 46 51 PM" src="https://user-images.githubusercontent.com/66372350/116912316-0cdcff80-ac16-11eb-804f-929c5a3a99c2.png">

Related support topic: https://wordpress.org/support/topic/video-with-corner-radius-not-working/#post-14394011
Example story URL: https://sgsite.cmsdevrel.com/web-stories/beauty-1/

- Plugin Version: 1.6.0
- WordPress Version:
- Operating System: iOS
- Browser: Chrome, Safari

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by miina** [comment] 2021-05-21 10:22
Closing this as a duplicate of #7524. Will re-open later if it comes out that fixing it on mobile devices will need a separate issue for some reason.

**Closed as completed by miina** 2021-05-21 10:22 UTC
Labels: Type: Bug, Status: Duplicate, Group: Media, Elements: Video, Browser Issues
