### ISSUE TITLE
Text element "lock" behavior for height and width adjustments

### ISSUE THREAD

**Issue by o-fernandez** [GoogleForCreators/web-stories-wp#3637] opened 2020-08-03 19:48 UTC
## Feature Description

If the text element is "locked", the user can edit either height or width and the overall shape and font size will change accordingly. 
If the text element is "unlocked", the user can only edit text width, as text height can't be adjusted independently or it'd lead to line height issues. 

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by barklund** [comment] 2020-10-08 22:32
Is this issue basically a duplicate of #1950, or how does it differ? If they're duplicates, just close this one.

**Comment by miina** [comment] 2020-10-09 06:36
Hmm, it's not a duplicate in theory but in practice it is.

Closing as duplicate of #1950.

**Closed as completed by miina** 2020-10-09 06:36 UTC
Labels: Status: Duplicate, Type: Enhancement, P2, Elements: Text, Group: Selection, Group: Workspace
