### ISSUE TITLE
Delete doesn't work immediately after undo

### ISSUE THREAD

**Issue by o-fernandez** [GoogleForCreators/web-stories-wp#1852] opened 2020-05-19 12:33 UTC
## Bug Description

If you undo a deletion, then press the del key right after, the element is not deleted. 

## Expected Behaviour

It should delete as usual.

## Steps to Reproduce

1. Add text element to page
2. Click on page to deselect the text element
3. Re-select the text element
4. Press delete key, see element get deleted
5. Press cmd+z or ctrl+z to undo, element reappears and is shown as selected
6. Press delete key again -- notice that the element is not deleted. 

Workaround: Need to deselect and re-select the item in order to delete. 

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by miina** [comment] 2020-05-20 16:49
This should be a duplicate of #1781

**Comment by miina** [comment] 2020-05-20 16:50
The issue here is that the Delete shortcut isn't working globally -- clicking anywhere resulting in losing focus of the Page will disable using Delete shortcut.

**Closed as completed** 2020-06-05 18:12 UTC
Labels: Type: Bug, P2, Group: History
