### ISSUE TITLE
Applying Style To Text in Highlighted State - Editor Crash

### ISSUE THREAD

**Issue by csossi** [GoogleForCreators/web-stories-wp#1756] opened 2020-05-13 14:09 UTC
## Bug Description

If user highlights text and THEN selects an alignment option (left, vertical, etc.), the editor crashes

## Expected Behaviour

Expected text element to respond to alignment selection

## Steps to Reproduce

- add a text element
- enter text within 
- highlight the text just entered
- select "Align Left" (or one of the other alignment options)

## Screenshots

![image](https://user-images.githubusercontent.com/16945664/81823021-d63c3f80-9501-11ea-9322-513a6d656dc9.png)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by o-fernandez** [comment] 2020-05-14 14:22
Duplicate of #1483

**Closed as completed by o-fernandez** 2020-05-14 14:22 UTC
