### ISSUE TITLE
Divi + Advanced Custom Fields: conflicts with editor

### ISSUE THREAD

**Issue by ernee** [GoogleForCreators/web-stories-wp#4492] opened 2020-09-15 05:41 UTC
## Bug Description

As reported [in this issue](https://github.com/google/web-stories-wp/issues/4406), when the [Divi theme](https://www.elegantthemes.com/gallery/divi/) and[ Advanced Custom Fields plugin](https://wordpress.org/plugins/advanced-custom-fields/) are activated on a site, the editor experiences a strange overlay and console errors:

<img width="1255" alt="Screen Shot 2020-09-10 at 10 51 34 PM" src="https://user-images.githubusercontent.com/8108643/93169751-a03ee000-f6da-11ea-9d98-81f09c05eb8c.png">

Note the editor is still usable, but only deactivation of either makes the issue go away.  

## Expected Behaviour

The editor works properly with the Divi theme and the Advanced Custom Fields (free/ pro) plugin.

## Steps to Reproduce

1) Activate the Divi Theme and Advanced Custom Fields plugin
2) Create a new story or open the editor from a template
3) See the strange overlay and console errors 

## Additional Context

- Plugin Version: 1.0.0-rc.1
- Operating System: MacOS
- Browser: Chrome

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by LuckynaSan** [comment] 2020-10-27 20:35
The issue no longer persists with Divi version 4.6.6, Advanced Custom Fields version 5.9.1, and Web Stories 1.1.0-alpha all activated together. In my own testing, I was able to create a new story and use an existing template.

**Comment by swissspidy** [comment] 2020-10-28 14:22
@LuckynaSan reopened?

**Comment by LuckynaSan** [comment] 2020-10-28 14:32
@swissspidy Hi Pascal, I am reopening this to test a little further since it seems the issue can still be reproduced by @ernee.

**Comment by LuckynaSan** [comment] 2020-11-02 16:13
Quick follow up, we were able to reproduce this issue and discovered that the overlay error message (Failed to initialize plugin: et_quicktags) in the editor media panel no longer displays when this ["Disable the visual editor when writing"](https://jmp.sh/QJK7yDH) setting in the user profile is checked.

**Comment by swissspidy** [comment] 2022-04-13 21:02
I think we can close this for now; doesn't seem to be a high priority thing that still happens.

**Closed as completed by swissspidy** 2022-04-13 21:02 UTC
Labels: Type: Bug, Status: Not Applicable, Type: Support
