### ISSUE TITLE
Support Variable Fonts in a Different Language

### ISSUE THREAD

**Issue by LuckynaSan** [GoogleForCreators/web-stories-wp#4614] opened 2020-09-22 14:54 UTC
## Feature Description

A user requested support for Arabic fonts.

## Additional Context

> Support for Arabic fonts, since currently, default Arabic font is available and no one from Arabic publishers like to use it. That would open huge opportunities in the Arab world with Arabic publishers

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment] 2020-09-22 15:01
Sounds like a feature request for Google Fonts?

Or a duplicate of #1260?

**Comment by o-fernandez** [comment] 2020-09-28 18:15
I'm currently tracking these requests, but worth noting that major Desktop story editing tools have built support for custom fonts, which may be a good solution that may help in this case as well.

**Comment by swissspidy** [comment] 2020-09-28 18:28
See  #4717 for custom font support

**Comment by swissspidy** [comment] 2020-12-14 14:15
Closing in favor of #4717 and #1260

**Closed as completed by swissspidy** 2020-12-14 14:15 UTC
Labels: Status: Duplicate, Type: Enhancement, Internationalization (I18N), Group: Fonts, Group: Workspace
