### ISSUE TITLE
Remove drop indicators when trying to reorder pages in carousel (compact mode - no thumbnail shown)

### ISSUE THREAD

**Issue by csossi** [GoogleForCreators/web-stories-wp#2797] opened 2020-06-28 02:17 UTC
## Bug Description

I am unable to click-and-drag bars to reorder pages (WAI), yet drop indicators are shown.

## Expected Behaviour

No drop indicators should be displayed.

## Steps to Reproduce

1. Try to drag an drop pages in the carousel when it is in compact mode (i.e. on smaller screens).
2. Observe that drop indicators are shown, despite not supporting the reordering in compact mode.

## Screenshots

Video:
https://drive.google.com/file/d/1VAGw-z_XI2eUPIvPj4NSG4hnTmqGZ8zI/view

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment] 2020-06-28 06:44
AFAIK that‘s currently working as intended, as reordering without seeing what you reorder doesn‘t make much sense. See #2575.

Although we should definitely not show the blue drop indicators in that case...

~Can someone perhaps update the issue description as per our issue template for bugs?~ Edit: did it myself

**Comment by dvoytenko** [comment] 2020-07-10 00:30
@swissspidy I'd agree, but not entirely. Moving Nth to Mth spot is definitely not likely. But I think moving Nth to N+1 spot is not so far-fetched.

**Comment by o-fernandez** [comment] 2020-08-19 14:49
I think in new designs with the visual pass we'll stop minimizing the thumbnails, so you should never be in this position. Will close this in favor of addressing as part of #3088

**Closed as completed by o-fernandez** 2020-08-19 14:49 UTC
Labels: Type: Bug, P2, Group: Carousel
