### ISSUE TITLE
Duplicating page will cause workspace area to shift up and lock in position and pages are not saved after force refresh.

### ISSUE THREAD

**Issue by samitron7** [GoogleForCreators/web-stories-wp#5262] opened 2020-11-12 15:45 UTC
## Bug Description

There are 2 related issues here:
1. Duplicating page will cause workspace area to shift up and lock in position. 
2. You'll be forced to refresh to 'unshift' the workspace.

- Pages are not saved after force refresh.

- In my attempt to replicate the same bug, I noticed the second time around, refreshing does nothing to restore shifting of the workspace upward. It remained locked in this position. You can view that story [here](https://stories-new-wordpress-amp.pantheonsite.io/wp-admin/post.php?action=edit&post=13514#page=%252299bdf2ea-d39d-4476-933b-21f1d1662ae6%2522)

## Expected Behaviour

The workspace should not shift up and stay locked and added pages should be saved and not lost on refresh.

## Steps to Reproduce

1. Duplicate a page many time till you've exceeded the number of visual thumbnails on the screen. I added 15 pages. Note that the workspace will shift up and you will not be able to scroll.
2. Go into grid view to check the number of pages. I see 16 pages.
3. Refresh the page. Notice that there are no longer 16 pages in the thumbnail carousel or in grid view.
4. I repeated step 1-3 and this time around (second video), refreshing the page did not restore the position of the workspace. It remained stuck (view story linked in the description to see). Notice that I also tried to delete story pages and then refresh. That did not work.
 
## Screenshots

![thumbnailIssues.gif](https://images.zenhubusercontent.com/5e9dc6e34754fda9ccd26e86/1e6f09b2-8ef0-41a9-93cb-2f020f195c34)
![thumbrefresh.gif](https://images.zenhubusercontent.com/5e9dc6e34754fda9ccd26e86/63c95eb3-5410-4c28-a31d-850e466a8543)

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment] 2020-11-12 16:07
Seems like a possible duplicate of #5077

**Comment by miina** [comment] 2021-05-25 15:20
Wasn't able to reproduce this anymore, seems to have gotten fixed meanwhile.

**Closed as completed by miina** 2021-05-25 15:20 UTC
Labels: Type: Bug, Group: Workspace, Type: UX Quality
