### ISSUE TITLE
Issue with Fill

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#958] opened 2020-04-01 23:57 UTC
## Bug Description

The fill does not consistently work.

## Expected Behaviour

Fill should expand the image  and fill the entire page
## Steps to Reproduce

1. Add an image to a page
2. Decrease the size of the image by dragging from a corner
3. Press the fill button
4. Notice that the image is brought to the top left corner as the existing size

## Screenshots

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by barklund** [comment] 2020-04-01 23:59
@jauyong duplicate of #942.

**Closed as completed** 2020-04-02 05:35 UTC
Labels: Status: Duplicate
