### ISSUE TITLE
Adding New Text - Cursor Focus

### ISSUE THREAD

**Issue by csossi** [GoogleForCreators/web-stories-wp#1755] opened 2020-05-13 14:04 UTC
## Bug Description

Can add text, but expected cursor focus to be in text field

## Expected Behaviour

expected that cursor focus would be within the field (with any assistive text within the field highlighted - expected that user can just go ahead and type without haveing to highlight/remove text

## Steps to Reproduce

Opt to add new text box

## Screenshots

![image](https://user-images.githubusercontent.com/16945664/81822415-118a3e80-9501-11ea-8808-7c75d42552a0.png)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by jauyong** [comment] 2020-05-15 01:35
@csossi I don't quite follow what the issue is. 
is it related to this? #830

**Comment by swissspidy** [comment] 2020-05-15 10:37
Related: #1608

**Comment by o-fernandez** [comment] 2020-05-28 22:06
I will close this in favor of #1608

**Closed as completed by o-fernandez** 2020-05-28 22:06 UTC
Labels: Type: Bug, P2, Elements: Text
