### ISSUE TITLE
Quick actions menu

### ISSUE THREAD

**Issue by o-fernandez** [GoogleForCreators/web-stories-wp#5896] opened 2021-01-12 14:56 UTC
## Feature Description

Some actions are cumbersome in the editor as it's difficult to find them in the Design panel. As such, we should implement a quick actions menu that shows up when an element is selected, with the appropriate actions easily accessible by the user. 

Key actions to include: 
- Change color (text, shapes)
- Change font (text only)
- B/I/U (text only)
- Crop (media only)
- Add link

Some of these elements may not be necessary if they are present in the Right-click/Context menu #97 

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by aaecheverria** [comment] 2021-01-28 00:31
Hi @o-fernandez @choumx @bmattb  ,

I'm sharing the Figma file with the right Quick Actions Menu design and flows. We will have a hand-off session this week to go over this, but in the mean time feel free to add your comments/questions:

https://www.figma.com/file/NHHMwIfxMnz39NxqkrFb7R/Stories---Post-Stable?node-id=4462%3A0

**Comment by o-fernandez** [comment] 2021-02-01 15:27
Generally these look good (both right click and context), but we should iterate on sequencing and scope based on eng feedback.

**Comment by BrittanyIRL** [comment] 2021-05-18 18:16
Hey @bmattb - this ticket is duplicative of the epic. Do you want to keep it around or close it?

**Comment by swissspidy** [comment] 2021-06-09 16:58
Closing as duplicate of #6147

**Closed as completed by swissspidy** 2021-06-09 16:58 UTC
Labels: Status: Duplicate, Type: Enhancement, Elements, Group: Canvas
