### ISSUE TITLE
Plugin post install banner

### ISSUE THREAD

**Issue by samitron7** [GoogleForCreators/web-stories-wp#2912] opened 2020-07-01 18:47 UTC
Post install, display a banner to welcome and guide users. Copies can be found [here](https://docs.google.com/document/d/1Dbjt9AXIWg9AdcJs2qSDwxmCa5vHJtHQ_t3uAN5pBI0/edit#heading=h.2d83f6r6hu5x)

**Comment by swissspidy** [comment] 2020-07-01 19:16
Duplicate of #2853

**Closed as completed** 2020-07-01 19:16 UTC
Labels: Status: Duplicate, UX Needed
