### ISSUE TITLE
Easier/smarter text font & color styling for text sets fails on black on black.

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#8919] opened 2021-09-01 19:26 UTC
## Bug Description

Originally reported by @samwhale 
Inserting black text on a black background doesn’t change the text color to white

![image22](https://user-images.githubusercontent.com/58738530/131731773-8815d8a3-72ed-4192-8059-2a98b464b6cf.gif)

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by miina** [comment] 2021-09-08 15:28
Closing this being unable to reproduce it (by original reporter - Samuel - either).

The only Text sets that don't get the color applied are the ones that already have a different color used in the text set, these text sets are inserted with default color as per design.

**Closed as completed by miina** 2021-09-08 15:28 UTC
Labels: Type: Bug, P1, Group: Text Sets
