### ISSUE TITLE
Shape style panel - colour picker hidden by panel

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#6802] opened 2021-03-17 13:38 UTC
## Bug Description

Color picker can be hidden by screen if the design panel is scrolled too far down. It can be fixed by scrolling it up just a little bit (see gif)

## Screenshots

![image22](https://user-images.githubusercontent.com/58738530/111476188-4dcf9200-8704-11eb-8ade-7543d4252f94.gif)

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by barklund** [comment] 2021-03-30 13:45
Duplicate of #6719 (which is almost fixed).

**Closed as completed by barklund** 2021-03-30 13:45 UTC
Labels: Type: Bug, Elements: Shape, Group: Saved Styles
