### ISSUE TITLE
Use explicit media URLs for hosting instead of relying on Wordpress hosting

### ISSUE THREAD

**Issue by shishirm** [GoogleForCreators/web-stories-wp#6986] opened 2021-04-01 17:20 UTC
## Feature Description

Provide the ability to circumvent Wordpress based hosting and instead use explicit URLs for media. This allows hosting to be built off the tool where cheaper options may be available.

So essentially, you are able to add content (video, images, gifs) to the media library via a URL and the content will continue to live on the original host instead of actually being uploaded into the Wordpress media library.

## Alternatives Considered

No alternatives exist and is a big pain point for creators at the moment, especially if a Story were to go viral and get a lot of traffic.

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment] 2021-04-02 10:28
Hi there,

We're tracking the ability to embed media given a URL in #471. Please subscribe to that ticket for any updates.

Duplicate of #471

**Closed as completed by swissspidy** 2021-04-02 10:28 UTC
Labels: Status: Duplicate, Type: Enhancement, Group: Media
