### ISSUE TITLE
CSS issues 

### ISSUE THREAD

**Issue by mxbclang** [GoogleForCreators/web-stories-wp#7997] opened 2021-06-21 16:00 UTC
## Bug Description

When using the Select Stories option in the Web Stories block, the search icon, fields, and text for the Stories and Search by Author fields are misaligned.

## Expected Behaviour

Search fields will be properly aligned.

## Steps to Reproduce

- Go to a page or post
- Using Block Editor, add Web Stories block
- Click Select Stories
- The Search fields in the upper-right corner are misaligned

## Screenshots

![image](https://user-images.githubusercontent.com/12189958/122791347-25b57900-d287-11eb-9785-7d87abf40800.png)

## Additional Context

- Plugin Version: 1.8.0
- WordPress Version: 5.7.2
- Operating System: macOS Big Sur
- Browser: Replicated in both Chrome 91 and Firefox 89

Also noting that I was able to replicate this on a clean WP install, so it does not appear to be caused by any kind of conflict.

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by miina** [comment] 2021-06-21 16:14
Duplicate of https://github.com/google/web-stories-wp/issues/7991
cc @spacedmonkey 

Edit: looks like both of the issues have similar information so closing this as a duplicate.

**Closed as completed** 2021-06-21 16:18 UTC
Labels: Type: Bug, Status: Duplicate
