### ISSUE TITLE
Unable to set Page Color when Background Added

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#1032] opened 2020-04-03 16:50 UTC
## Bug Description

If you add an image or video as the background, you are not able to set the page "style" or colour.

Related: #1177

## Expected Behaviour

I should be able to set a page colour even when there is a background. 

## Steps to Reproduce

1. set a background on a page.
2. try to add a colour to the page

## Screenshots

Page has a background, can't set colour
![image](https://user-images.githubusercontent.com/5874851/78385264-96507700-75a9-11ea-99ad-53b2246a3211.png)

Page has no background, can set colour
![image](https://user-images.githubusercontent.com/5874851/78385320-a700ed00-75a9-11ea-9fcb-4fcd3e49103f.png)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by barklund** [comment] 2020-05-19 21:23
Already covered by #1177 - this can be closed as duplicate.

**Comment by wassgha** [comment] 2020-06-04 05:40
Closed as duplicate of #1177 , will be fixed by #1925

**Closed as completed by wassgha** 2020-06-04 05:40 UTC
Labels: Type: Bug, Status: Duplicate, P1, Group: Canvas
