### ISSUE TITLE
Audio in Media Library

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#52] opened 2019-11-30 20:54 UTC
## Feature description

Find elegant way to display audio in the media gallery when you need it.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by swissspidy** [comment] 2020-04-23 08:29
Related: #48

**Comment by swissspidy** [comment] 2021-12-14 23:12
Duplicate of #8585

**Closed as completed by swissspidy** 2021-12-14 23:12 UTC
Labels: Type: Enhancement, Status: Needs More Info, Elements
