### ISSUE TITLE
Rebar plugin conflicts with Stories Embed Block 

### ISSUE THREAD

**Issue by ernee** [GoogleForCreators/web-stories-wp#3245] opened 2020-07-16 22:16 UTC
## Bug Description

As reported in [this issue](https://github.com/google/web-stories-wp/issues/3086), the [Rebar- Reading Progress Bar plugin ](https://codecanyon.net/item/rebar-reading-progress-bar-for-wordpress-website/23941493) can prevent the Stories Embed Block from rendering properly (spinner continuously loading, story title visible). 

Troubleshooting revealed blocking this file from the Rebar plugin allowed the embed to complete loading:

/wp-content/plugins/rebar/js/rebar.min.js?ver=2.0.2 

([Contents here](http://snippi.com/s/zbzc8gc))

The user temporarily disabled the plugin as well and it allowed the embed to complete loading. 

## Expected Behaviour

The Stories embed should fully render and function without issue. 

## Screenshots

![rebar plugin conflicts with story embed block](https://user-images.githubusercontent.com/8108643/87728033-14aae080-c777-11ea-9ad7-89f0d6109030.png)

## Additional Context

- Plugin Version: 1.0.0-beta.1

Rebar Plugin 2.0.2

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment] 2020-07-17 10:08
I think I know where the problem is.

Both this script and the amp-story-player script use `window.onload` to initialize their scripts.

That's not really a good practice because only 1 function can be added to `window.onload`, so the last one wins. In this case, the Rebar script was probably loaded after the player's script.

I will report this upstream.

**Comment by swissspidy** [comment] 2020-07-17 10:20
Upstream issue: https://github.com/ampproject/amphtml/issues/29335

**Comment by swissspidy** [comment] 2020-07-20 09:03
Since the upstream issue was fixed on Friday, it should get promoted to the Beta channel tomorrow, and then the Stable channel next Tuesday ([as per the docs](https://amp.dev/documentation/guides-and-tutorials/learn/spec/release-schedule/#beta-and-experimental-channels))

Temporarily switching to the Nightly channel at https://cdn.ampproject.org/experiments.html I was able to verify that the issue was indeed resolved.

**Closed as completed by swissspidy** 2020-07-20 09:03 UTC
Labels: Group: Integration, AMP Format, Group: WordPress, Type: Support

**Comment by Dennis-95** [comment] 2020-07-21 01:22
i'm not 100% sure if i did it corretly, but i switched on the nightly mode on my domain (claudia-makeup.com) in this way
![Cattura](https://user-images.githubusercontent.com/45852903/88001795-4ae2ba00-cb01-11ea-9d76-13beaa7638f2.PNG)

then i cleared the cache with rebar plugin up but is seems that it's always stucked in infinite loading.
Can you confirm i did it correctly?

**Comment by swissspidy** [comment] 2020-07-21 09:15
@Dennis-95 That looks correct, but it seems like WP Rocket is interfering, as the `https://cdn.ampproject.org/amp-story-player-v0.js` script is not loaded at all. If I visit https://claudia-makeup.com/idee-make-up/tendenze-estate-2020/?nocache to disable WP Rocket it works just fine. As previously mentioned at #3086, try **disabling** the _Combine JavaScript files_ option in WP Rocket.

![file-lQzhZAPJnv](https://user-images.githubusercontent.com/841956/88036155-738ba380-cb43-11ea-9241-07cc74957d5a.png)

**Comment by Dennis-95** [comment] 2020-07-23 13:00
> @Dennis-95 That looks correct, but it seems like WP Rocket is interfering, as the `https://cdn.ampproject.org/amp-story-player-v0.js` script is not loaded at all. If I visit https://claudia-makeup.com/idee-make-up/tendenze-estate-2020/?nocache to disable WP Rocket it works just fine. As previously mentioned at #3086, try **disabling** the _Combine JavaScript files_ option in WP Rocket.
> 
> ![file-lQzhZAPJnv](https://user-images.githubusercontent.com/841956/88036155-738ba380-cb43-11ea-9241-07cc74957d5a.png)

I tried to exclude your url from wp rocket optimization and it seems working now, thanks!
Should i wait the next update to have this fix public right?

Thankd and best regards

PS: I'm working on a new post with some issues i faced in release today

**Comment by swissspidy** [comment] 2020-07-29 14:44
> Should i wait the next update to have this fix public right?

Yes. We're looking into how we can improve the compatibility with WP Rocket and other plugins so that you don't have to manually change the options to fix this.
