### ISSUE TITLE
A long duration in a Pan of background image exposes part of a background

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#5722] opened 2020-12-17 14:32 UTC
## Bug Description

When a background image is used, and there is a long pan (10+ seconds) duration placed on that image, there is a sliver of content on the left hand side that appears to be brighter then the rest of the content.

Example:
![Screen Shot 2020-12-17 at 9.28.41 AM.png](https://images.zenhubusercontent.com/5e8b274ee5c3c7dfddf4be62/7a8f2a21-a531-490e-a2f8-047f71f64866)

Zoom/enhance on left margin:
![Screen Shot 2020-12-17 at 9.28.46 AM.png](https://images.zenhubusercontent.com/5e8b274ee5c3c7dfddf4be62/94fdf840-961e-4886-8279-b9e24ea76a07)

Zoomed max power:
![Screen Shot 2020-12-17 at 9.30.17 AM.png](https://images.zenhubusercontent.com/5e8b274ee5c3c7dfddf4be62/910623cf-3b7b-4eab-be74-a7698968de9a)

## Expected Behaviour

Background image should appear with the same consistent presentation throughout.

## Steps to Reproduce

Some examples:

1. https://www.theconsciousplantkitchen.com/web-stories/making-almond-flour-thumbprint-cookies/ - Note that all pages are showing a line of the background image with greater brightness
2. https://stories-new-wordpress-amp.pantheonsite.io/wp-admin/post.php?post%3D14306%26action%3Dedit%23page%3D%252522955064a2-946d-450a-8bd7-91ba9a2f2fdc%252522&sa=D&ust=1608218645324000&usg=AOvVaw29VUsNxEoUkLfHx30SLtIA

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by BrittanyIRL** [comment] 2021-11-03 19:07
I'm not able to reproduce this, moving to QA to see if Claudio sees it.

**Comment by csossi** [comment] 2021-11-16 20:53
Unable to reproduce, @BrittanyIRL

**Closed as completed** 2021-11-16 20:56 UTC
Labels: Type: Bug, Group: Animations
