### ISSUE TITLE
Remove publisher-logo-src fallback to WordPress logo

### ISSUE THREAD

**Issue by o-fernandez** [GoogleForCreators/web-stories-wp#4772] opened 2020-09-30 20:04 UTC
## Bug Description

Currently, we fallback to using the generic WP logo if a user has not set a publisher logo. We should not do that moving forwrad.

## Expected Behaviour

If there's no publisher logo, keep empty, instead of using WP logo as fallback.  

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment] 2020-09-30 20:22
Duplicate of #4762

**Closed as completed by swissspidy** 2020-09-30 20:22 UTC
Labels: Type: Bug, P2
