### ISSUE TITLE
Color opacity field and hex value disappear if opacity is set to 0%

### ISSUE THREAD

**Issue by samitron7** [GoogleForCreators/web-stories-wp#5401] opened 2020-11-23 17:38 UTC
## Bug Description

Color opacity field and hex value disappear if opacity is set to 0%

## Expected Behaviour

1. Add a shape
2. Change the opacity under Style in the design panel to 0%
3. Expect the opacity to change to 0% 

## Steps to Reproduce

1. Add a shape
2. Change the opacity under Style in the design panel to 0%
3. Observe that the hex value has disappeared along with the opacity textfield.

Same result if you change opacity to zero inside the color picker.

## Screenshots

![Screen Shot 2020-11-23 at 9.27.41 AM.png](https://images.zenhubusercontent.com/5e9dc6e34754fda9ccd26e86/5787a5b6-8862-40ff-8d5f-ca8014dbc0d3)

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment] 2020-11-23 21:03
@barklund I think you‘ve filed this already?

**Comment by barklund** [comment] 2020-11-23 22:05
Yes, duplicate of https://github.com/google/web-stories-wp/issues/5369

**Closed as completed** 2020-11-24 10:43 UTC
Labels: Type: Bug, Status: Duplicate, Elements: Shape
