### ISSUE TITLE
Flaky test: E2E test SVG, heading-order

### ISSUE THREAD

**Issue by spacedmonkey** [GoogleForCreators/web-stories-wp#6897] opened 2021-03-23 15:27 UTC
## Bug Description

[Example](https://github.com/google/web-stories-wp/runs/2170673029?check_suite_focus=true#step:15:9).

The error is in this test `SVG › not should be to select SVG as publisher logo`

With the following output

```
expect(received).toPassAxeTests(expected)

    Expected page to pass Axe accessibility tests.
    Violations found:
    Rule: "heading-order" (Heading levels should only increase by one)
    Help: https://dequeuniversity.com/rules/axe/4.1/heading-order?application=axe-puppeteer
    Affected Nodes:
      #f55a20d6-ac49-4b3a-9e83-620729dbfbb2
        Fix ANY of the following:
        - Heading order invalid
```

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment] 2021-03-23 15:47
Duplicate of #6893 I think. It's not actually flakey, but consistently failing due to a bug.

**Closed as completed** 2021-03-24 10:27 UTC
Labels: Type: Bug, Status: Duplicate, Type: Infrastructure, Package: E2E Tests
