### ISSUE TITLE
Background video not shown in Page Preview

### ISSUE THREAD

**Issue by miina** [GoogleForCreators/web-stories-wp#1019] opened 2020-04-03 12:58 UTC
## Bug Description

It looks like background videos don't show up in Page Preview nor Grid View

## Expected Behaviour

Background video should be visible in Page preview and Grid View.

## Steps to Reproduce

1. Add a Video
2. Set it as background
3. See the Page carousel previews / grid.

## Screenshots

<img width="1138" alt="Screenshot 2020-04-03 at 14 56 59" src="https://user-images.githubusercontent.com/3294597/78363105-82ae0c00-75bb-11ea-9602-e69e8839c769.png">
<img width="246" alt="Screenshot 2020-04-03 at 14 56 01" src="https://user-images.githubusercontent.com/3294597/78363124-89d51a00-75bb-11ea-964c-defa69b238f0.png">

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment] 2020-04-03 13:19
Duplicate of #999

**Closed as completed by swissspidy** 2020-04-03 13:19 UTC
Labels: Type: Bug, Status: Duplicate
