### ISSUE TITLE
Video Available For Use On Page Before Fully Uploaded

### ISSUE THREAD

**Issue by csossi** [GoogleForCreators/web-stories-wp#1910] opened 2020-05-20 19:53 UTC
## Bug Description

A video dragged from user's PC to canvas or media panel is available for a user to use (move, crop, etc.) BEFORE it is fully uploaded. Seems to "disappear" to user

## Expected Behaviour

Thought that perhaps the video would be greyed out in the media panel or canvas - or something to show the user that it hasn't finished uploading

## Steps to Reproduce

Dragged this video to Media Panel:
![image](https://user-images.githubusercontent.com/16945664/82490348-1fb3fe00-9ab1-11ea-8a3d-921c23ecb988.png)

Was able to click it and add it to the canvas:
![image](https://user-images.githubusercontent.com/16945664/82490412-35c1be80-9ab1-11ea-8c82-63fc0404293b.png)

After a minute or two, video has disappeared from Media Panel:
![image](https://user-images.githubusercontent.com/16945664/82490625-8a653980-9ab1-11ea-811e-02059e66fce2.png)

NOTE: User CAN still click the video in teh canvas and the video will play
NOTE: On Preview, video appears as an image
NOTE: Nothing, neither video nor image, appears in the Media Library (which is what I'd expect)

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment] 2020-05-20 19:57
One more NOTE, as an fyi: Tried to upload the video by clicking "Upload" in the media panel. It's a 10,514 kb mp4 file and it does indeed fail:

![image](https://user-images.githubusercontent.com/16945664/82491390-969dc680-9ab2-11ea-8e2e-68e884a81966.png)

**Comment by o-fernandez** [comment] 2020-05-28 22:15
The video disappearing from the media panel seems concerning. @diegovar is this something the team could look at?

**Comment by swissspidy** [comment] 2020-05-28 22:34
I think what‘s happening is this:

1. Drag video from computer to editor
1. Video is added to media library and usable on canvas immediately while being uploaded (a feature!)
1. Video fails to upload (e.g. some unexpected server error)
1. Video is removed again from library because it never actually uploaded successfully

**Comment by o-fernandez** [comment] 2020-05-28 22:37
Oh, in that case there are two things to do if the video fails: 
* Tell user that upload failed when they drag video onto canvas
* Disable/remove the video from canvas

This may be more on Workspace then? @barklund

**Comment by miina** [comment] 2020-06-30 08:24
@merapi Did #2730 fix this as well?

**Comment by merapi** [comment] 2020-06-30 08:42
No, #2730 took care of happy path upload when dropped on canvas. Upload failure case is still TBD (more on this [here](https://github.com/google/web-stories-wp/issues/2706#issuecomment-649059315)). A low effort fix is to remove all elements using the given resource (NOTE: blob issues still can happen thanks to history).

**Comment by swissspidy** [comment] 2020-06-30 09:21
@merapi So this report here is essentially the upload failure case from #2730, right?

**Comment by merapi** [comment] 2020-06-30 09:40
I think we need to clarify what is expected here, because "Video Available For Use On Page Before Fully Uploaded" sounds like a feature, not a bug 😉  (should we disable any operation on video element? blob can still play and be cropped, so not sure) and another thing is a failure case.

**Comment by swissspidy** [comment] 2020-06-30 09:54
Yes, that is a feature. But please read my comment https://github.com/google/web-stories-wp/issues/1910#issuecomment-635643869:

Video is added to media library and usable on canvas immediately while being uploaded -> Video fails to upload -> Video is removed again from library because it never actually uploaded successfully

**Comment by merapi** [comment] 2020-06-30 10:05
> @merapi So this report here is essentially the upload failure case from #2730, right?

Correct (the bug part) and exact behavior should be discussed further, because "Disable/remove the video from canvas" [will not fix all the issues](https://github.com/google/web-stories-wp/issues/2706#issuecomment-649059315).

My point regarding this issue was that the Expected Behaviour is not clear or this issue should be removed/renamed.

**Comment by diegovar** [comment] 2020-07-07 05:35
Does this need further clarification? Is the real issue that a failed upload didn't show a snackbar describing that it failed?

**Comment by swissspidy** [comment] 2020-07-07 05:38
@diegovar Yes, that‘s my understanding as per the conments above. Exact behavior needs to be defined first.

**Comment by swissspidy** [comment] 2020-07-07 16:59
Duplicate of #2706

**Closed as completed by swissspidy** 2020-07-07 16:59 UTC
Labels: Type: Bug, Status: Duplicate, Status: Not Applicable, P2
