### ISSUE TITLE
Time stamp of published story is not accurate

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#4450] opened 2020-09-10 19:27 UTC
## Bug Description

I published a story to a site and checked the dashboard for it's status. It's showing as published 27 minutes ago, however that is when I began creating the story, as I published it less than 2 minutes ago

## Expected Behaviour

I would expect that the Published X minutes ago would be the time that it was published, not created.

## Screenshots

![Screen Shot 2020-09-10 at 3.23.56 PM.png](https://images.zenhubusercontent.com/5e8b274ee5c3c7dfddf4be62/ee17490b-88ba-47d5-931d-da94474eaaaf)

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment] 2020-09-10 19:29
Duplicate of #4095

**Closed as completed by swissspidy** 2020-09-10 19:29 UTC
Labels: Type: Bug, Status: Duplicate, Group: Dashboard
