### ISSUE TITLE
Undo (CMD-Z) not restoring deleted background image

### ISSUE THREAD

**Issue by o-fernandez** [GoogleForCreators/web-stories-wp#1405] opened 2020-04-30 12:45 UTC
## Bug Description

Undo should revert my last update. If I delete the background of a page, this is not working. 

## Expected Behaviour

The background should be restored if I trigger an undo right after deleting the background. 

## Steps to Reproduce

1. Delete background image on a page
2. Trigger cmd+z (undo)

## Screenshots

Hard to show, as it's all keyboard stuff. 

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by o-fernandez** [comment] 2020-04-30 12:47
NOTE: CMD+Z also does not "set as background" the image if I press it right after I trigger "remove as background", so it's not limited to just deleting the background.

**Comment by jauyong** [comment] 2020-05-13 17:25
groomed on may 13. ready to sprint planning

Morten has  PR that may fix this.

**Comment by barklund** [comment] 2020-05-14 18:02
Duplicate of #1191

**Closed as completed** 2020-05-19 18:50 UTC
Labels: Type: Bug, Status: Duplicate, P1, Group: History
