### ISSUE TITLE
Browser refreshes causes saved colours in the colour picker to be lost

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#8915] opened 2021-09-01 18:19 UTC
## Bug Description

Originally reported by @aaskedall 

Refreshing the browser caused saved colours to be lost

## Expected Behaviour
Saved colours should be retained.

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by swissspidy** [comment] 2021-09-01 20:17
Duplicate of #8914

**Closed as completed by swissspidy** 2021-09-01 20:17 UTC
Labels: Type: Bug, Group: Saved Colors

**Comment by bmattb** [comment] 2021-09-01 21:04
I don't even know how this happened here.
