### ISSUE TITLE
WPGlobus compatibility: Published story url's html is incomplete, prevents story display

### ISSUE THREAD

**Issue by therightshiftllc** [GoogleForCreators/web-stories-wp#3583] opened 2020-07-31 16:26 UTC
## Request

When visiting a published story's url, the html is invalid/incomplete, resulting in only some plain text displayed (the story is not displayed.)

Examples:
https://www.wiccangathering.com/stories/wiccan-intro-free-download/
https://www.wiccangathering.com/stories/wiccan-spells/

## Additional Context
![Story-WiccanSpells-html](https://user-images.githubusercontent.com/69049759/89055841-b823f580-d320-11ea-99aa-15a16d136690.png)
![WiccanSpells-Story-Render](https://user-images.githubusercontent.com/69049759/89055842-b8bc8c00-d320-11ea-8556-41f6b2fb3b06.png)

- Plugin Version: 1.0.0-beta.1
- Operating System: Win10 64bit
- Browser: Post created and link tested in Chrome Version 84.0.4147.89

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by ernee** [comment] 2020-07-31 21:51
@therightshiftllc thanks for reporting!

I can see the issue at the story URLs. I'm curious if a plugin or service is involved because this is not common after publishing a story. 

I see you have several optimizations applied on the main site's URL. If possible, could you temporarily disable the Humming Bird plugin and Cloudflare's Rocket Loader (perhaps placing Cloudflare temporarily in [development mode](https://support.cloudflare.com/hc/en-us/articles/200168246-Understanding-Cloudflare-Development-Mode)) to see if the issue resolves?

If not, could you provide your [Site Health information](https://i.imgur.com/Rtkmsba.png).

**Comment by therightshiftllc** [comment] 2020-08-03 14:15
Hi Renee,

I have deactivated Hummingbird and SG Optimizer plugins and put Cloudflare
in dev mode. Still doesn't seem to be working.

`
### wp-core ###

version: 5.4.2
site_language: en_US
user_language: en_US
permalink: /%postname%/
https_status: true
user_registration: 0
default_comment_status: open
multisite: false
user_count: 3
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /home/customer/www/wiccangathering.com/public_html
wordpress_size: 3.30 GB (3545246540 bytes)
uploads_path: /home/customer/www/
wiccangathering.com/public_html/wp-content/uploads
uploads_size: 304.46 MB (319253185 bytes)
themes_path: /home/customer/www/
wiccangathering.com/public_html/wp-content/themes
themes_size: 7.86 MB (8237831 bytes)
plugins_path: /home/customer/www/
wiccangathering.com/public_html/wp-content/plugins
plugins_size: 114.33 MB (119888414 bytes)
database_size: 35.61 MB (37335137 bytes)
total_size: 3.75 GB (4029961107 bytes)

### wp-active-theme ###

name: Twenty Twenty (twentytwenty)
version: 1.4
author: the WordPress team
author_website: https://wordpress.org/
parent_theme: none
theme_features: automatic-feed-links, custom-background, post-thumbnails,
custom-logo, title-tag, html5, align-wide, responsive-embeds,
customize-selective-refresh-widgets, editor-color-palette,
editor-font-sizes, editor-styles, widgets, menus, editor-style
theme_path: /home/customer/www/
wiccangathering.com/public_html/wp-content/themes/twentytwenty

### wp-themes-inactive (1) ###

Neve: version: 2.7.2, author: ThemeIsle (latest version: 2.7.5)

### wp-plugins-active (27) ###

410 for WordPress: version: 0.8.7, author: Samir Shah
Beaver Builder Plugin (Standard Version): version: 2.3.2.6, author: The
Beaver Builder Team (latest version: 2.3.2.7)
Duplicator: version: 1.3.36, author: Snap Creek
Easy Social Sharing: version: 1.3.3, author: ThemeGrill
Etsy Shop: version: 2.3, author: Frédéric Sheedy
Gallery Custom Links: version: 1.2.7, author: Jordy Meow
GDPR Cookie Consent Banner: version: 2.3.15, author: termly
Health Check & Troubleshooting: version: 1.4.4, author: The WordPress.org
community
Insert Headers and Footers: version: 1.4.6, author: WPBeginner
jQuery Pin It Button for Images: version: 3.0.5, author: Marcin Skrzypiec
MC4WP: Mailchimp for WordPress: version: 4.8, author: ibericode
MC4WP: Mailchimp Top Bar: version: 1.5.2, author: ibericode
Menu Image: version: 2.9.6, author: Rui Guerreiro
NewsPlugin: version: 1.0.17, author: newsplugin.com
Shared Counts: version: 1.3.0, author: Bill Erickson & Jared Atchison
Simple 301 Redirects: version: 1.07, author: Scott Nellé
Smush: version: 3.6.3, author: WPMU DEV
Structured Content: version: 1.4.4, author: Gordon Böhme, Antonio Leutsch
Subscribers.com: version: 1.5.1, author: Subscribers.com
Tasty Pins: version: 1.1.0, author: WP Tasty
UpdraftPlus - Backup/Restore: version: 1.16.26, author: UpdraftPlus.Com,
DavidAnderson
Web Stories: version: 1.0.0-beta.1, author: Google
WPGlobus: version: 2.4.14, author: WPGlobus (latest version: 2.4.17)
WP Old Post Date Remover: version: 3.0.7, author: Ben Meredith
WP Quiz: version: 2.0.5, author: MyThemeShop
WProofreader: version: 2.5, author: WebSpellChecker
Yoast SEO: version: 14.5, author: Team Yoast (latest version: 14.6.1)

### wp-plugins-inactive (4) ###

Hummingbird: version: 2.4.2, author: WPMU DEV (latest version: 2.5.1)
SG Optimizer: version: 5.5.8, author: SiteGround (latest version: 5.6.1)
Social Media Follow Buttons Bar: version: 4.59, author: Space X-Chimp
Swap Google Fonts Display: version: 1.0.6, author: Gijo Varghese

### wp-media ###

image_editor: WP_Image_Editor_GD
imagick_module_version: Not available
imagemagick_version: Not available
gd_version: bundled (2.1.0 compatible)
ghostscript_version: 9.27

### wp-server ###

server_architecture: Linux 3.12.18-clouder0 x86_64
httpd_software: Apache
php_version: 7.3.20 64bit
php_sapi: cgi-fcgi
max_input_variables: 3000
time_limit: 120
memory_limit: 768M
max_input_time: 120
upload_max_size: 128M
php_post_max_size: 128M
curl_version: 7.66.0 OpenSSL/1.1.1g-fips
suhosin: false
imagick_availability: false
server-headers:
date: Mon, 03 Aug 2020 14:14:13 GMT
content-type: text/html; charset=UTF-8
vary: Accept-Encoding
expires: Wed, 11 Jan 1984 05:00:00 GMT
cache-control: no-cache, must-revalidate, max-age=0
link: <https://www.wiccangathering.com/wp-json/>; rel="https://api.w.org/"
x-httpd: 1
host-header: 192fc2e7e50945beb8231a492d6a8024
x-proxy-cache: BYPASS
x-proxy-cache-info: D NC:100000 UP:1
cf-cache-status: DYNAMIC
cf-request-id: 04564553a0000083c98d2bc200000001
expect-ct: max-age=604800, report-uri="
https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
server: cloudflare
cf-ray: 5bd0a4cc3dea83c9-ORD
content-encoding: br
alt-svc: h3-27=":443"; ma=86400, h3-28=":443"; ma=86400, h3-29=":443";
ma=86400
htaccess_extra_rules: false

### wp-database ###

extension: mysqli
server_version: 5.7.25-28-log
client_version: mysqlnd 5.0.12-dev - 20150407 - $Id:
7cc7cc96e675f6d72e5cf0f267f48e167c2abb23 $

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /home/customer/www/
wiccangathering.com/public_html/wp-content
WP_PLUGIN_DIR: /home/customer/www/
wiccangathering.com/public_html/wp-content/plugins
WP_MAX_MEMORY_LIMIT: 768M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: false
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_LOCAL_DEV: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable

`

**Comment by ernee** [comment] 2020-08-05 03:00
@therightshiftllc thanks so much for the details. I'm currently testing the plugins you have active on the site to see if there is a conflict. While I have yet to encounter the issue, I wanted to check a few things:

1) Could you share what you have placed in the **Insert Headers and Footers** plugin?

2) Would you happen to have a test site where you can safely test the Stories plugin with the other plugins deactivated?

I see you have the Health Check Troubleshooting plugin installed, however its troubleshooting mode only affects the logged-in user view. 

From what I can tell, we'll need to be able to preview the story as a logged out user (unless the issue also occurs while you preview the published story logged in?).  Thanks!

**Comment by therightshiftllc** [comment] 2020-08-06 13:45
Renee, here is what I have in Headers and Footers. Only the header has
added code; body and footer do not.

Header:

```
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="
https://www.googletagmanager.com/gtag/js?id=UA-153087296-2"></script>
<script data-ad-client="ca-pub-1202834743384518" async src="
https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-153087296-2');
</script>
<script
id="mcjs">!function(c,h,i,m,p){m=c.createElement(h),p=c.getElementsByTagName(h)[0],m.async=1,m.src=i,p.parentNode.insertBefore(m,p)}(document,"script","
https://chimpstatic.com/mcjs-connected/js/users/53cb38ad700024e17416f38ed/ccd496cd12b89428642598fa4.js
");</script>
<script data-ad-client="ca-pub-1202834743384518" async src="
https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
```

I do not have a staging site.

I’m not clear on what you mean about the Health Check plug-in and the
logged in/out user. Could you explain a bit more what you’re asking for?

**Comment by ernee** [comment] 2020-08-06 21:55
@therightshiftllc thanks for the info! 

> I do not have a staging site.
> 
> I’m not clear on what you mean about the Health Check plug-in and the
> logged in/out user. Could you explain a bit more what you’re asking for?

My apologies. I saw you had the **Health Check and Troubleshooting** plugin and assumed you may have already tried its [troubleshooting mode](https://make.wordpress.org/support/handbook/appendix/troubleshooting-using-the-health-check/#troubleshooting). This mode disables active plugins and switches to a default theme safely because it only affects the experience of the logged-in user. It may not help in this case since the issue affects the public URLs.

With that said, could you confirm if [the preview](https://jmp.sh/LzZcJNa) of the published story while logged in renders for you?

Also, if you use one of the pre-made templates under [_Explore Templates_](https://jmp.sh/iP3WVMw) and publish the story, does it render in an incognito/ private browser window?

**Comment by therightshiftllc** [comment] 2020-08-07 15:49
Hi Renee,

Actually I didn't know about the troubleshooting mode in that plugin.
Thanks for telling me, I just tried it and it looks like the offending
plugin is WPGlobus. With only Stories and WPGlobus enabled, I can replicate
the non-rendered preview.

Also without troubleshooting mode, the preview is also *not *rendered for a
logged-in user.

**Comment by ernee** [comment] 2020-08-07 22:55
@therightshiftllc thanks so much for following up and nice troubleshooting ;)!

So while I'm not able to replicate the exact issue you're experiencing, I do notice display issues and AMP validation errors when I view a story after configuring certain settings in [WPGlobus](https://wordpress.org/plugins/wpglobus/). 

In my testing, they were not immediately reversible with toggling off these settings under _Post Types_ and _Compatibility_ in their settings: 

<img width="1095" alt="WPGlobus Post Types" src="https://user-images.githubusercontent.com/8108643/89694580-ef1c7d00-d8c5-11ea-97bc-6d9de527ed2d.png">
<img width="1088" alt="WPGlobus Compatibility" src="https://user-images.githubusercontent.com/8108643/89694587-f5125e00-d8c5-11ea-8ccd-893d4114c20a.png">


We may have to review compatibility with this plugin further. In the meantime, could you ensure those items are  _toggled off_   (if they are not already) and let us know if that resolves the issue for you?

**Comment by therightshiftllc** [comment] 2020-08-10 13:44
Hi Renee,

Yes I have both of those post types disabled, but the issue is still
present.

**Comment by swissspidy** [comment] 2020-08-10 14:28
@therightshiftllc Could you perhaps try removing the plugin and installing this in-development version? We've made a few recent changes that might solve your issue here. Download: [web-stories.zip](https://github.com/google/web-stories-wp/files/5051406/web-stories.zip)

**Comment by therightshiftllc** [comment] 2020-08-11 15:51
Hi Pascal, I removed the plugin and installed the one you sent. I'm still
seeing the same thing, no change.

**Comment by ernee** [comment] 2020-09-14 22:11
Hi @therightshiftllc! We're still investigating this issue as it seems can vary from site to site. 

In the meantime, could you let us know if the most recent version of the plugin 1.0.0-rc.1 also shows this conflict (it's currently available as an update or you can download the [new version here](https://wp.stories.google/))?

**Comment by therightshiftllc** [comment] 2020-09-25 22:05
Hi Renee, I tried version 1.0.0 via WordPress update. I still have the same
problem with this new version with my current install. (It did work with
all other plugins disabled though.)

**Comment by ernee** [comment] 2020-09-29 19:13
@therightshiftllc thanks for the update!

**Comment by ernee** [comment] 2020-10-07 03:30
@therightshiftllc just a follow up that we're looking into a couple ways to address this issue. We've opened [this issue](https://github.com/WPGlobus/WPGlobus/issues/90) with WPGlobus and we're also [working on a way](https://github.com/google/web-stories-wp/pull/4513) to prevent the story URLs from being affected by other plugins. 

Thanks for your early report and patience as we look into some possible solutions. We'll update the issue with more information as we have it.

**Comment by ernee** [comment] 2020-10-28 21:01
@therightshiftllc WPGlobus just [released a fix ](https://github.com/WPGlobus/WPGlobus/issues/90#issuecomment-717303162)in version 2.5.15 that might help. 

Could you update and let us know if your stories display now?

**Comment by therightshiftllc** [comment] 2020-10-29 15:16
Hi Renee, I just updated and the page still isn't displaying properly. The
html is different now though.

https://www.wiccangathering.com/web-stories/wiccan-spells/

**Comment by ernee** [comment] 2020-10-30 18:24
@therightshiftllc really appreciate the follow up!

1) Just to confirm: this is with version 1.1.0 of the Web Stories plugin?

2) To pinpoint if it is just WPGlobus or possibly another plugin involved in your case (on my test site the issues I encountered resolved with the update), could you use the Health Check Troubleshooting mode again? 

Perhaps compare enabling Web Stories first, then WPGIobus to see if it is the cause. I  recall you mentioned that the issue also occurs when you preview/ view the story while logged in so that should provide an accurate view.

**Comment by ernee** [comment] 2020-11-07 01:19
Just noting here that I am able to recreate the issue with the incomplete/ nearly blank story doing the following:

1) _Builders support_ enabled on under _WPGlobus > Compatibility_ :

<img width="1264" alt="Screen Shot 2020-11-06 at 3 49 09 PM" src="https://user-images.githubusercontent.com/8108643/98426924-c1271000-204f-11eb-8909-5a580c432849.png">

2) Additional language(s) configured in the settings _and_  corresponding translations set for the _Site Title_  under _Settings > General_: 

<img width="674" alt="Screen Shot 2020-11-06 at 5 08 59 PM" src="https://user-images.githubusercontent.com/8108643/98427639-cb96d900-2052-11eb-9d72-06b812dd3a03.png">

incomplete/ nearly blank story:

<img width="690" alt="Screen Shot 2020-11-06 at 5 06 30 PM" src="https://user-images.githubusercontent.com/8108643/98427910-00eff680-2054-11eb-8a6b-7fe43deb35d2.png">

Disabling the option in WPGlobus, and then editing and updating the story allows it to render per testing (might be best to try in a test environment).

**Comment by LuckynaSan** [comment] 2021-02-18 20:07
With Web Stories v1.4.0 and WPGlobus 2.6.5 activated, the issue is no longer reproducible with the configuration outlined above. This issue will be closed, but if you encounter any other issues please feel free to open a <a href="https://wordpress.org/support/plugin/web-stories/#new-post">new support topic</a>. Thank you!

**Closed as completed by LuckynaSan** 2021-02-18 20:07 UTC
Labels: Type: Bug, Group: Integration, Type: Support
