### ISSUE TITLE
Color picker bug when switching input

### ISSUE THREAD

**Issue by barklund** [GoogleForCreators/web-stories-wp#541] opened 2020-03-11 20:23 UTC
## Bug Description

When switching from one color input to the next without closing the color picker in-between, the second input magically (and wrongly) gets the color from the first input in stead of opening the color picker with the new input's color.

## Expected Behaviour

When color picker opens, it should always reset to the state of the color input clicked and never remember its own state.

## Steps to Reproduce

1. Select a text element
2. Open color picker for text color
3. Set a new color for the text (this step is necessary)
4. Without closing the color picker, click to open color picker for background color.
5. See text color being magically copied to background color.

## Screenshots

Demo of bug in action: https://youtu.be/yiHLssknDnc

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment] 2020-04-21 13:43
Looks like this is a duplicate of #1042 and #1196. Fixed by #1187.

**Closed as completed by swissspidy** 2020-04-21 13:43 UTC
Labels: Type: Bug, Status: Duplicate, Group: Editing
