### ISSUE TITLE
Paste and Match styles doesn't preserve pre-existing styling applied to text

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#4591] opened 2020-09-21 14:40 UTC
## Bug Description

If a user sets a style on text (font, colours) on a text element, then pastes text into that element using the browser "Paste and match styles" the formatting previously applied is not applied to the pasted text and the style must be reapplied.

## Expected Behaviour

Text pasted into a text element with styling already applied using "Paste and match styles" should preserve the styling that is already in place and render the text with said styling applied.

## Steps to Reproduce

1. Create a text element and update the font and colour
2. Copy some text into your clipboard
3. Select into the text element and bring up the context menu
4. Select "Paste and match style"

## Additional Context

This appears to be working fine in RC1

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by barklund** [comment] 2020-09-21 16:03
Duplicate of #1605

**Closed as completed by barklund** 2020-09-21 16:03 UTC
Labels: Type: Bug, Status: Duplicate, P1, Elements: Text, Group: Copy/Paste
