### ISSUE TITLE
Elements dragged to the bottom make workspace UI unusable

### ISSUE THREAD

**Issue by pbakaus** [GoogleForCreators/web-stories-wp#1119] opened 2020-04-09 02:12 UTC
## Bug Description

When elements are positioned so that they're behind the thumbnails and workspace UI, all of these stop to work.

## Expected Behaviour

You should be able to still use all editor UI if an element is clipped at the bottom.

## Steps to Reproduce

Make a image big. Drag it so that it is under the "new page" button. Try adding a new page. See it fail and start crying.

## Screenshots

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by pbakaus** [comment] 2020-04-09 02:12
@wassgha or @dvoytenko can you take a look at this one?

**Comment by swissspidy** [comment] 2020-04-09 05:04
Duplicate of #1088

**Closed as completed** 2020-04-09 06:57 UTC
Labels: Status: Duplicate, P0
