### ISSUE TITLE
Element edges/borders incorrect when part of the element is outside of canvas

### ISSUE THREAD

**Issue by o-fernandez** [GoogleForCreators/web-stories-wp#1787] opened 2020-05-14 16:02 UTC
## Bug Description

If I create an element (shape, images) and drag them down to below the bottom edge of the canvas their selection area is incorrectly placed as starting from the bottom to the canvas up, covering other parts of the canvas where the shape/image is not. 

## Steps to Reproduce

1. Add shape
2. Drag shape partially outside of canvas
3. select element

## Screenshots

Video: 
[Odd selection3.mov.zip](https://github.com/google/web-stories-wp/files/4629531/Odd.selection3.mov.zip)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment] 2020-05-14 16:18
Duplicate of #1571?

**Comment by miina** [comment] 2020-05-26 13:40
@wassgha Are you planning to work on this anytime soon? Checking for issues to pick up and looks like this has been assigned for 2 weeks without a PR.

**Comment by wassgha** [comment] 2020-05-26 22:57
> @wassgha Are you planning to work on this anytime soon? Checking for issues to pick up and looks like this has been assigned for 2 weeks without a PR.

Hey @miina , yes. I didn't have a computer for a while so there will be a PR coming for this

**Comment by barklund** [comment] 2020-05-28 18:34
Hi @wassgha, can you check if [this](https://docs.google.com/presentation/d/1ZiZWrmLiX40rt3n_1LMSGJxYWI-xsWFsS9bkzdbRIV8/edit?ts=5ec35b92#slide=id.g77fdc779d5_0_280) is a related problem or separate from this?

**Comment by wassgha** [comment] 2020-05-29 07:56
@barklund unclear but probable, I'd check if we can get a link to the story or a way to reproduce it.

**Closed as completed** 2020-06-05 22:16 UTC
Labels: P0
