### ISSUE TITLE
Create v1 data model and API for custom page templates

### ISSUE THREAD

**Issue by barklund** [GoogleForCreators/web-stories-wp#7054] opened 2021-04-05 18:41 UTC
## Feature Description

Custom page templates are pages created by end users, that can be saved and easily recalled from any other story. Basically it's one big storage of single-page templates that can be accessed by all users of the same WordPress installation with the correct permissions (more on permissions later).

All page-level properties can be saved to a page template including elements, background element, background color, and animations.

Story-level properties are **not** saved along with a page template including settings like status, publication date, page advancement, excerpt, saved colors and styles, etc.

See visual user flow in [this Figma section](https://www.figma.com/file/NHHMwIfxMnz39NxqkrFb7R/Stories---Post-Stable?node-id=7082%3A531446).

### Terminology

**Page templates** is the name for this feature as exposed to end users.

**Story templates** is the name for the pre-designed full-story examples, that user can also take advantage of. These are two separate concepts.

However, for ease of communication internally, we can call the former ***layouts*** and the latter ***templates*** to properly distinguish these. That's up to the API to define.

### Access model

* Any user that can create a story, can create or delete a custom layout/page template
* A custom layout/page template is a big JSON blob, no meta-data.
* A custom layout/page template cannot be edited, only deleted
* Any user that can create a story, can list all the custom layouts/page templates sorted by creation date descending (newest first).
* There will be no need for other sort methods or even filters.
* Pagination might be needed in the long run, but probably not for v1
* Search is also not needed for v1, but perhaps later we can search the actual text string in the JSON blob for matches?

### Possible implementations

There are basically two possible implementation models with each their advantages and drawbacks.

#### Treat similar to global colors, no separate API

This concept is to treat the page templates as "just" another list of globally-editable (for all WP-users that is) JSON objects stored and accessed similar to the existing global colors.

✅ **Advantages:**
* Easy implementation in both server and client
* Number of requests identical to current implementation

🚫 **Drawbacks:**
* Larger data-transfer on every story load/save
* Doesn't scale well
* Only saves page templates on story save

#### Separate API to list, create, and delete page templates

This concept is to create a completely new API to create, delete and list page templates using WP's existing API framework.

✅ **Advantages:**
* Future-proof, scales well
* Limits request size on story load/save
* Saves page templates immediately when added

🚫 **Drawbacks:**
* More complex implementation in both server and client
* More requests performed overall

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment] 2021-04-05 19:03
Thanks, I already opened #6965 for this. Will consolidate.

There are some open questions about capabilities (which user roles can do what)

**Comment by barklund** [comment] 2021-04-05 19:06
> Thanks, I already opened #6965 for this. Will consolidate.

I just checked the epic and as it didn't have any children, I added this one. Didn't actually check any further. But thanks!

**Comment by swissspidy** [comment] 2021-04-06 14:00
Duplicate of #6965

Closing in favor of #6965

**Closed as completed by swissspidy** 2021-04-06 14:00 UTC
Labels: Status: Duplicate, Type: Enhancement, P1
