### ISSUE TITLE
Select all (cmd+a) not selecting all elements on a page

### ISSUE THREAD

**Issue by o-fernandez** [GoogleForCreators/web-stories-wp#1406] opened 2020-04-30 12:58 UTC
## Bug Description

Select all (cmd+a) not selecting all elements on a page, it is instead selecting a bunch of text from the editor menus. 

## Expected Behaviour

All elements on the page, in the editor workspace, should be selected. 

## Steps to Reproduce

1. Create a new page
2. Add a few elements (e.g., shapes, text elements, etc.)
3. Press cmd+a

Tested on Mac OS Version 10.15.4 (19E287) and Chrome Version 81.0.4044.122 (Official Build) (64-bit)

## Screenshots

Video attached

[select all (cmd-a) not working.mov.zip](https://github.com/google/web-stories-wp/files/4558405/select.all.cmd-a.not.working.mov.zip)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment] 2020-04-30 13:09
Not a bug from a technical PoV as we haven't really implemented global shortcuts like this _yet_.

I suggest closing in favor of #355, which covers that part.

cc @jauyong

**Comment by miina** [comment] 2021-07-06 07:45
Closing as this has been implemented meanwhile.

**Closed as completed by miina** 2021-07-06 07:45 UTC
Labels: Type: Enhancement, P2, Group: Workspace
