### ISSUE TITLE
Oversized Elements Blocking Page Buttons

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#1055] opened 2020-04-05 15:03 UTC
## Bug Description

When there’s an oversized element on top of the page controls, they become impossible to click

## Expected Behaviour

I should be able to click on those button even if an element is covering them

## Steps to Reproduce

1. Add an element to the page
2. increase the size so that it expands over the page controls
3. try to use the create new page button

## Screenshots
![image](https://user-images.githubusercontent.com/5874851/78502034-ef94e380-772c-11ea-9f4e-28b6ef5419b5.png)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment] 2020-04-08 06:58
Duplicate of #1088

**Closed as completed by swissspidy** 2020-04-08 06:58 UTC
Labels: Status: Duplicate, P1
