### ISSUE TITLE
Very confused as to how to use our color presets

### ISSUE THREAD

**Issue by o-fernandez** [GoogleForCreators/web-stories-wp#2308] opened 2020-06-08 16:26 UTC
## Bug Description

See video, when I added a color to color presets, it was sometimes shown, sometimes wasn't, depending on the element I clicked. 

For example, see how I switch to page 1 and can't apply the preset color either from the picker or the color presets section.

## Expected Behaviour

1. I open the color picker to apply a color to an element (shape and text) that can accept a color value. Clicking on the "Add to color preset" button should add the color to the Preset section in the Design Panel.

2. When selecting other elements with a primary color attribute (e.g., page background) I should always have the option to apply the color preset from presets in the Design Panel. 

## Screenshots

[Unclear how to add color presets and use them across element types](https://drive.google.com/open?id=1er60GtTRxcJlo-pwuvr6ER18BbKJsH3y)

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by miina** [comment] 2020-06-08 16:39
@o-fernandez Note that Page Background presets were currently purposefully left out from implementing since it wasn't clear how to implement this or if it should be completely hidden instead. (There's the ongoing Slack discussion on Color Presets)

Perhaps we should combine these under one issue? Or change the issue title to "Implement Color Presets for Page Background" to reflect what's being discussed on Slack?

**Comment by miina** [comment] 2020-06-08 16:41
Also: The issue that should get this fixed is #1837 -- its description is just not entirely accurate anymore since there has been quite a lot of discussion meanwhile...

**Comment by o-fernandez** [comment] 2020-06-09 14:06
> @o-fernandez Note that Page Background presets were currently purposefully left out from implementing since it wasn't clear how to implement this or if it should be completely hidden instead. (There's the ongoing Slack discussion on Color Presets)
> 
> Perhaps we should combine these under one issue? Or change the issue title to "Implement Color Presets for Page Background" to reflect what's being discussed on Slack?

I'm OK combining all these issues into one, agree that there are various issues. Let's discuss how to consolidate/break out the various issues and decide on what to do here. Will follow-up. 

@samitron7 @jauyong @miina FYI

**Comment by samitron7** [comment] 2020-06-09 14:38
@o-fernandez I updated the expected behavior to reflect that there is only color preset and that is in the design panel. Zewen (original designer who worked in this), Daniel and I came to the conclusion that 1) presets need to be outside of the color preset because its main goal it to provide efficiency and allow you to quickly add a saved color 2) it was unnecessary to duplicate function (ie have presets in 2 location) inside the color picker

**Comment by csossi** [comment] 2020-06-15 17:22
Verified in QA

**Comment by samitron7** [comment] 2020-06-18 06:52
I see 2 issues:
1. When I select the page, shape or text the color options should be the same. Currently, if I select text I get white and black but selecting shape and page yields a lot more colors.

2. This one is minor but because of the scrollbar, when I select a any element then the page, color swatches (and really everything on the panel) shifts a bit.

Only #1 needs to be fixed and we should file a feature enhancement for #2

**Comment by miina** [comment] 2020-06-18 09:21
@samitron7 Ah, thanks for the note.

The text colors are currently separately because the text colors don't support any gradients. Does this mean that we would gray out the colors which are not suitable for the Text (all gradients) the same way as we do for Page?

Also, will this stay this way -- that the color options are the same for page, shape, or text? Or will it change back in the future? Asking to understand if to do that as a temporary change or not.

**Comment by miina** [comment] 2020-06-18 09:45
Closing this issue:
Added a new issue for 1. -- https://github.com/google/web-stories-wp/issues/2585
Added a follow-up issue for 2. -- https://github.com/google/web-stories-wp/issues/2586

**Closed as completed by miina** 2020-06-18 09:45 UTC
Labels: Type: Bug, P0, Group: Saved Colors
