### ISSUE TITLE
Stories Global Settings Page

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#1518] opened 2020-05-04 20:38 UTC
Add in the "Stories Global Settings" page. 
- Visible when "Editor Settings" is clicked in left nav. 
- Has the ability to return back to dashboard view (last view or back to my stories?)
- Has the ability to enter Google Analytics Tracking ID
    - Needs an API
- Has the ability to upload logos for stories as Publisher Logos
    - Needs an API

![Stories Global Settings.png](https://images.zenhubusercontent.com/5e9dcd9a9ff5dfdaffcdf132/3d518550-c66b-466f-a71c-c971aa016350)

Questions: 
- What does error handling on these forms look like?

**Comment by swissspidy** [comment] 2020-05-04 21:33
Duplicate of #570? One should be closed

**Closed as completed** 2020-05-04 23:37 UTC
Labels: Group: Dashboard
