### ISSUE TITLE
Fatal Error when running plugin from source

### ISSUE THREAD

**Issue by ghost** [GoogleForCreators/web-stories-wp#2961] opened 2020-07-03 11:03 UTC
## Bug Description

The plugin could not be activated because it triggered a fatal error.

## Steps to Reproduce

1. Install the plugin
2. Activate the plugin

## Screenshots
![image](https://user-images.githubusercontent.com/49720173/86463201-afa0c500-bd4a-11ea-9c6c-a14dac7f4314.png)

## Additional Context

- Wordpress version: 5.4.2
- Plugin Version: 1.0.0 beta.1
- Operating System: Windows 10 64bit
- Browser: Chrome Version 83.0.4103.116 (Official Build) (64-bit)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment] 2020-07-03 11:13
Hi @BagthariyaSumit,

Thanks for your report!

If you download the plugin straight from GitHub, you will only get the _source_ files, not the final _build_ that includes all JavaScript and PHP files to run the editor. That's why  you get the error about classes not being found.

To prevent this, please download the ready-to-use version from from https://google.github.io/web-stories-wp/beta/

If you want to install the latest master version instead, follow our[ Getting Started guide](https://github.com/google/web-stories-wp/blob/master/docs/getting-started.md) for contributors.

In the meantime, we'll work on making the message a bit clearer for cases like yours. You can follow progress on that in #1234

**Comment by swissspidy** [comment] 2020-07-09 20:11
Fixed by #2962.

Duplicate of #1234.

**Closed as completed by swissspidy** 2020-07-09 20:11 UTC
Labels: Status: Duplicate, Group: WordPress, Type: Support

**Comment by swissspidy** [comment] 2020-07-16 16:10
Forgot one case in #2962, see #3231
