### ISSUE TITLE
Snap guides should be contained within the page

### ISSUE THREAD

**Issue by samitron7** [GoogleForCreators/web-stories-wp#5036] opened 2020-10-28 05:53 UTC
## Bug Description

Snap guides are bleeding off the page

![Mask Group.png](https://images.zenhubusercontent.com/5e9dc6e34754fda9ccd26e86/a304ca92-0445-4cbe-97c2-b6d16f36265a)

## Expected Behaviour

1. Snap guides should reside within the page.
2. To better differentiate from the design safe zone, let's change the snap guides to dashed lines.

## Screenshots

![Screen Shot 2020-10-27 at 10.50.31 PM.png](https://images.zenhubusercontent.com/5e9dc6e34754fda9ccd26e86/e95cf40f-0c1d-4775-8a62-9a9862abfa0a)

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment] 2020-10-28 09:09
Duplicate of #2414

**Closed as completed by swissspidy** 2020-10-28 09:09 UTC
Labels: Type: Bug, Status: Duplicate, Group: Canvas, Group: Workspace
