### ISSUE TITLE
Warn user if video set to loop but longer than document auto-advance time

### ISSUE THREAD

**Issue by o-fernandez** [GoogleForCreators/web-stories-wp#2549] opened 2020-06-16 22:59 UTC
## Feature Description

In the case that a user:
* sets a video to "loop"
* sets document "auto-advance" to time X
* video is longer than X (longer than auto-advance time)

The page would auto-advance before one full loop of the video, which is probably undesired. We should warn the user about this and let them decide whether to change the video to "play once" instead of looping. 

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment] 2020-06-16 23:02
Duplicate of #2204?

**Closed as completed** 2020-06-17 10:32 UTC
Labels: Status: Duplicate, Type: Enhancement

**Comment by o-fernandez** [comment] 2020-06-17 14:16
I duped myself, how fun. Thanks for merging :)
