### ISSUE TITLE
Modifying Publish Date - Not Appearing In Dashboard

### ISSUE THREAD

**Issue by csossi** [GoogleForCreators/web-stories-wp#2823] opened 2020-06-30 02:42 UTC
## Bug Description

Modifying the Publish Date in Editor is not updating the Published date in Dashboard

## Expected Behaviour

updating the Publish Date in the editor should be reflected int he "Published" date in the Dashboard

## Steps to Reproduce

- open a Published story
- in Document panel, change Publication date
- Update story
- go to Dashboard and note Publication date

## Screenshots

Dashboard has:
![image](https://user-images.githubusercontent.com/16945664/86077226-9a314f80-ba59-11ea-8872-aa835844923b.png)

But I had modified date in Editor:
![image](https://user-images.githubusercontent.com/16945664/86077295-b6cd8780-ba59-11ea-9a74-4ac68154f89b.png)

## Additional Context

- Plugin Version:
- Operating System: Win10
- Browser:Chrome

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment] 2020-06-30 08:21
Hmm I don't see the same. When I edit your story it shows this date:

<img width="954" alt="Screenshot 2020-06-30 at 10 17 26" src="https://user-images.githubusercontent.com/841956/86101718-f11b4100-baba-11ea-9ec1-38b7142968f4.png">

Did you perhaps see another story in the dashboard? Or not fully update? When changing the publish date to a future date, the update button will say "Schedule" instead of "Update"

When I follow your steps to reproduce, I actually notice a bigger bug:

**Scheduled stories (post status: `future`, not `publish`) are actually not listed in the dashboard.**

**Comment by o-fernandez** [comment] 2020-06-30 13:21
> Hmm I don't see the same. When I edit your story it shows this date:
> 
> <img alt="Screenshot 2020-06-30 at 10 17 26" width="954" src="https://user-images.githubusercontent.com/841956/86101718-f11b4100-baba-11ea-9ec1-38b7142968f4.png">
> 
> Did you perhaps see another story in the dashboard? Or not fully update? When changing the publish date to a future date, the update button will say "Schedule" instead of "Update"
> 
> When I follow your steps to reproduce, I actually notice a bigger bug:
> 
> **Scheduled stories (post status: `future`, not `publish`) are actually not listed in the dashboard.**

@csossi can you review Pascal's feedback and retest?

**Comment by swissspidy** [comment] 2020-07-02 21:46
Note that I created #2951 for the behavior I reported above: scheduled stories are not visible in the dashboard at all.

**Comment by o-fernandez** [comment] 2020-07-13 15:56
@csossi I'm moving this to the QA column just because it needs more QA effort.

**Comment by csossi** [comment] 2020-07-14 15:19
I reported that the problem was the display in the Dashboard, not the editor

Here's what I changed the Publication date to in the Editor:
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/6c2dd910-d848-42b4-83e0-17d7f42352ed)

And here's what the Dashboard has:
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/0be537cb-fb04-489e-853a-68c8cf10d4e3)

**Comment by swissspidy** [comment] 2020-07-14 15:21
Ah, then this is simply a duplicate of #2199.

**Closed as completed by swissspidy** 2020-07-14 15:21 UTC
Labels: Type: Bug, Status: Duplicate, P1, Group: Dashboard
