### ISSUE TITLE
Safe zone should always be visible when moving/editing an element

### ISSUE THREAD

**Issue by o-fernandez** [GoogleForCreators/web-stories-wp#6367] opened 2021-02-12 18:06 UTC

**Comment by o-fernandez** [comment] 2021-02-12 18:16
@samitron7 I think this is already meant to be, so it may be a bug that it doesn't always show or it goes away. Can you confirm? Maybe a dupe of https://github.com/google/web-stories-wp/issues/5134

**Comment by samitron7** [comment] 2021-02-12 18:27
Yes, this ticket is a dupe of #5134.

**Comment by miina** [comment] 2021-03-24 12:07
@o-fernandez One clarification: "should always be visible when moving/editing an element" -- does this mean that it should also be visible when in edit mode for an element, e.g. for text or media? Or is this just when moving/rotating/resizing?

**Comment by o-fernandez** [comment] 2021-03-25 21:59
> @o-fernandez One clarification: "should always be visible when moving/editing an element" -- does this mean that it should also be visible when in edit mode for an element, e.g. for text or media? Or is this just when moving/rotating/resizing?

That's a good question, I think when editing text may be helpful as well, since I may type enough to add a new line that bleeds below the safe zone. But @samitron7 @choumx WDYT?

**Comment by csossi** [comment] 2021-04-06 00:17
Verified in QA

**Closed as completed** 2021-05-28 09:12 UTC
Labels: P1, Group: Canvas, Group: Workspace
