### ISSUE TITLE
Redesign: Add drag'n'drop media to media picker component

### ISSUE THREAD

**Issue by barklund** [GoogleForCreators/web-stories-wp#6532] opened 2021-02-25 02:22 UTC
## Feature Description

Add Drag'n'drop functionality to generic media picker component.

- [ ] Support dragging from the local file system
- [ ] Support dragging from the media library

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by samitron7** [comment] 2021-02-25 15:49
@barklund What is the ticket about? Isn't this functionality already supported?

**Comment by barklund** [comment] 2021-02-25 22:12
@samitron7, it's about dragging media from the media library and/or the local file system directly to the media picker component - this one in particular:

![Screen Shot 2021-02-25 at 17 12 00](https://user-images.githubusercontent.com/637548/109226361-a0b0cc00-778c-11eb-915d-0c35a7bec9f4.png)

Currently, you have to press the pencil to edit this image - you cannot just drag an image there.

**Comment by swissspidy** [comment] 2022-06-23 09:30
Duplicate of #558

**Closed as not planned by swissspidy** 2022-06-23 09:30 UTC
Labels: Type: Enhancement, Group: Style Panel, P3, Group: Workspace
