### ISSUE TITLE
Broken styling in story select dialog in gutenberg block

### ISSUE THREAD

**Issue by spacedmonkey** [GoogleForCreators/web-stories-wp#7991] opened 2021-06-21 12:31 UTC
## Bug Description

Styling of both search and auth search fields found in the gutenberg select stories screen have odd styling. 

## Steps to Reproduce

1. Create a new post
2. Create web stories block. 
3. Select selected stories.
4. Select any type
5. Click select stories
6. See dialog. 

#### WP 5.3
<img width="1904" alt="Screenshot 2021-06-21 at 13 16 37" src="https://user-images.githubusercontent.com/237508/122761434-230d5080-d294-11eb-82d7-a63c3d8b877d.png">

#### WP 5.5
<img width="1904" alt="Screenshot 2021-06-21 at 13 20 32" src="https://user-images.githubusercontent.com/237508/122761461-2c96b880-d294-11eb-8eb4-3a6420fc02b5.png">

#### WP 5.6
<img width="1904" alt="Screenshot 2021-06-21 at 13 21 41" src="https://user-images.githubusercontent.com/237508/122761499-38827a80-d294-11eb-8068-084bee997a15.png">

#### 5.7
<img width="1904" alt="Screenshot 2021-06-21 at 13 22 54" src="https://user-images.githubusercontent.com/237508/122761551-46d09680-d294-11eb-9d5b-8cbdc3cef625.png">

## Additional Context

- Plugin Version: 1.8
- WordPress Version: 5.4-5.7
- Operating System: macOS Big Sur
- Browser: Replicated in both Chrome 91 and Firefox 89

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Implementation Brief

Add E2E test with screenshot to stop this happening again.

**Comment by swissspidy** [comment] 2021-06-22 09:22
Duplicate of #7526

**Closed as completed by swissspidy** 2021-06-22 09:22 UTC
Labels: Type: Bug, Status: Duplicate, Group: Blocks
