### ISSUE TITLE
3rd Party Animated Gifs - Edit - Slider Not Working

### ISSUE THREAD

**Issue by csossi** [GoogleForCreators/web-stories-wp#8696] opened 2021-08-15 21:11 UTC
## Bug Description

I can move the slider fine when editing 3rd party images or videos, but cannot move the slider when trying to edit an animated gif

## Expected Behaviour

Should be able to expand/retract according to slider

## Steps to Reproduce

- edit or create new story
- insert 3rd party animated gif onto page
- double click to enter EDIT mode
- try to click-and-drag slider

## Screenshots

https://share.getcloudapp.com/p9uk5QG5

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment] 2021-08-16 12:35
Duplicate of #8504

**Closed as completed by swissspidy** 2021-08-16 12:35 UTC
Labels: Type: Bug
