### ISSUE TITLE
Colour Picker is Cutoff

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#961] opened 2020-04-02 00:12 UTC
## Bug Description

The Colour  picker is cut off
![image](https://user-images.githubusercontent.com/5874851/78197967-07324a80-7455-11ea-9062-1b6de1e6c71f.png)

## Expected Behaviour

1. Colour Picker box should not be cut off. 
2. Colour Picker should move as you scroll in the design panel

## Steps to Reproduce

1. Add a textbox
2. scroll down in the design panel so that the text colour picker is at the bottom or barely showing
3. open the colour picker
4. Notice the colour picker box is cut off and doesn't move as you scroll up in the design panel

## Screenshots

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by barklund** [comment] 2020-04-08 21:29
Note that this is a duplicate of #540.

**Comment by miina** [comment] 2020-04-09 06:43
^ cc @jauyong

**Comment by pbakaus** [comment] 2020-04-11 06:06
Closed due to being a duplicate.

**Closed as completed by pbakaus** 2020-04-11 06:06 UTC
Labels: Type: Bug, P0
