### ISSUE TITLE
Tech Debt: Add `Union` icon to the design system

### ISSUE THREAD

**Issue by samwhale** [GoogleForCreators/web-stories-wp#6623] opened 2021-03-04 20:38 UTC
## Feature Description

The `Union` icon is not in the design system. Let's move it from the editor the design system so we can use it like the other icons.
Location: https://github.com/google/web-stories-wp/blob/main/assets/src/edit-story/icons/union.svg

![image](https://user-images.githubusercontent.com/22185279/110027006-ab201800-7cee-11eb-829f-f8bad2a4ad59.png)

## Alternatives Considered

none

## Additional Context

This lives in the border radius panel: https://github.com/google/web-stories-wp/blob/main/assets/src/edit-story/components/panels/design/borderRadius/borderRadius.js#L155.

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by BrittanyIRL** [comment] 2021-04-05 20:54
(not a bug but would be nice to throw this into fixit week)

**Comment by BrittanyIRL** [comment] 2021-05-03 19:56
So actually, we'd decided to leave icons that aren't shared elsewhere in the codebase in the editor and dashboard, respectfully. The union icon is only needed in the editor and should remain put. I'm gonna close this ticket.

**Closed as completed by BrittanyIRL** 2021-05-03 19:56 UTC
Labels: Type: Enhancement, Group: Design System
