### ISSUE TITLE
Beauty template layer selection: TypeError: Cannot read property 'r' of undefined

### ISSUE THREAD

**Issue by ernee** [GoogleForCreators/web-stories-wp#3544] opened 2020-07-29 23:20 UTC
[Updated] Received the following error after holding Shift +  selecting two overlapping text layers (Bungee + Bungee shade font) in the Beauty template 

```
TypeError: Cannot read property 'r' of undefined
    in FP
    in Unknown
    in form
    in designPanel__Form
    in LF
    in zF
    in div
    in designInspector__TopPanels
    in div
    in designInspector__Wrapper
    in VF
    in div
    in inspectorContent__InspectorWrapper
    in hH
    in div
    in inspectorLayout__InspectorBackground
    in div
    in inspectorLayout__Layout
    in bH
    in div
    in dropTarget__Content
    in Unknown
    in div
    in dropTarget__DropTargetComponent
    in Fj
    in Unknown
    in SF
    in CH
    in QN
    in div
    in layout__InspectorArea
    in div
    in layout__WorkspaceLayout
    in Unknown
    in kH
    in Unknown
    in Dm
    in Unknown
    in OH
    in TH
    in div
    in layout__Area
    in section
    in layout__Editor
    in RH
    in Unknown
    in RN
    in Unknown
    in Ce
    in Unknown
    in RL
    in Unknown
    in sT
    in Unknown
    in oM
    in Unknown
    in bs
    in Unknown
    in xA
    in Unknown
    in Qc
    in Unknown
    in $l
    in QN
    in Se
    in te
    in NH
    in v
```

**Video:** 
https://recordit.co/ykGcmB8AXo

**Console errors:** 
<img width="1280" alt="Screen Shot 2020-07-29 at 4 11 56 PM" src="https://user-images.githubusercontent.com/8108643/88863186-1765f680-d1b7-11ea-97b2-cb539ed87927.png">

**Additional Info:**
Version: 1.0.0-rc.1
MacBook Air (13-inch)
Chrome Browser
 
Note: first page of Beauty Template still experiences shifting noted in #3248 (see video^)

**Comment by ernee** [comment] 2020-09-10 05:27
Looks like similar error report around selecting layers in this issue: https://github.com/google/web-stories-wp/issues/4354

**Comment by o-fernandez** [comment] 2020-09-24 22:29
@carlos-kelly @barklund Is this something Pea or Prometheus should look at?

**Comment by swissspidy** [comment] 2020-09-25 09:55
Looking at the stack trace here and from #4354, it seems like the presets panel is trying to destruct the color object? i.e. from the object `color: { r, g, b, a }`, but `color` is `undefined`.

Maybe need to add some checks here and there to ensure the data is in the right shape.

**Comment by swissspidy** [comment] 2020-10-07 15:58
See also steps to reproduce in #4832

**Comment by swissspidy** [comment] 2020-10-07 22:15
Duplicate of #4832

**Closed as completed by swissspidy** 2020-10-07 22:15 UTC
Labels: Type: Bug, Status: Duplicate, P1, Group: Style Panel, Group: Patterns, Group: Workspace
