### ISSUE TITLE
Text opacity field jumps to 100 once deleting last character

### ISSUE THREAD

**Issue by winterDroid** [GoogleForCreators/web-stories-wp#1963] opened 2020-05-25 05:28 UTC
## Bug Description

While deleting characters in the text opacity field, the value jumps back to 100 once everything is deleted.

## Expected Behaviour

Should be empty and set to 0 once submitted.

**Comment by o-fernandez** [comment] 2020-05-28 22:16
Seems related/dupe of #1419 so will close in favor of that one.

**Closed as completed by o-fernandez** 2020-05-28 22:16 UTC
Labels: Type: Bug, Elements
