### ISSUE TITLE
BG/frame needed for png in media library

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#1891] opened 2020-05-20 15:08 UTC
## Bug Description

Bound all images with a transparent bg. 
[Figma](https://www.figma.com/file/Cd9iacVknHK62RO4pRwb68/Stories-Editor?node-id=8228%3A0)

## Screenshots

![image.png](https://images.zenhubusercontent.com/5e985a7aea3104e101699670/713536a9-bcdf-410e-8277-4e24370e37a0)

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment] 2020-09-22 21:11
Duplicate of #1194

**Closed as completed by swissspidy** 2020-09-22 21:11 UTC
Labels: Type: Bug, Status: Duplicate, Group: Media
