### ISSUE TITLE
Zoom Capability When Editing

### ISSUE THREAD

**Issue by LuckynaSan** [GoogleForCreators/web-stories-wp#4649] opened 2020-09-23 14:10 UTC
## Feature Description

User requested feature to zoom in and out when creating or editing. 
## Alternatives Considered

You can use your trackpad or mouse to zoom in and out.

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment] 2020-09-23 14:11
@LuckynaSan FYI there's #4022 for this already 🙂

**Comment by swissspidy** [comment] 2020-09-23 14:11
Duplicate of #4022

**Closed as completed by swissspidy** 2020-09-23 14:11 UTC
Labels: Status: Duplicate, Type: Enhancement, Group: Canvas
