### ISSUE TITLE
Can't Use Delete key After Text Add Shortcut

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#1113] opened 2020-04-08 20:57 UTC
## Bug Description

After adding a textbox with the shortcut (+ icon in the element panel tab), you can't press delete to get rid of the textbox. It looks like the textbox is selected / in focus but the delete key doesn't work. if you click out and back onto the textbox, you can now use the delete key. 

## Expected Behaviour

I should be able to delete the textbox with the delete key after using the shortcut.

## Steps to Reproduce

1.  Click the text add short cut in the tabs (the plus in the element panel tab),
2.  Hit the delete key. 
3. Doesn't work.

## Screenshots

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by dvoytenko** [comment] 2020-04-08 21:03
Duplicate of #738.

**Closed as completed by dvoytenko** 2020-04-08 21:03 UTC
Labels: P2
