### ISSUE TITLE
Text highlight vertically centers differently inside in editor versus preview 

### ISSUE THREAD

**Issue by MaxBittker** [GoogleForCreators/web-stories-wp#2788] opened 2020-06-26 17:10 UTC
![image](https://user-images.githubusercontent.com/5915546/85882720-ca54c600-b7ad-11ea-8e06-cfc68e963057.png)
^ I made this text box in the editor, by setting a padding and a highlight color.

![image](https://user-images.githubusercontent.com/5915546/85882934-27507c00-b7ae-11ea-906f-136fd5b17321.png)

^when I hit preview, the text was at the top of the highlight instead of in the center.

Story link, if you can view this: https://stories-labs.dev/maxbittker/?post_type=web-story&p=3561&preview=true

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment] 2020-06-26 17:16
Did you perhaps edit something in the meantime? Now the preview seems alright:

<img width="511" alt="Screenshot 2020-06-26 at 19 14 52" src="https://user-images.githubusercontent.com/841956/85883480-5af8c980-b7e1-11ea-86d0-7564c19e0440.png">

Although I see that you made the text box quite tall:

<img width="957" alt="Screenshot 2020-06-26 at 19 13 30" src="https://user-images.githubusercontent.com/841956/85883514-66e48b80-b7e1-11ea-9969-9cf9849e2286.png">

That definitely shouldn't be necessary to achieve good line height.


---

Note: perhaps a duplicate of #2201?

**Comment by MaxBittker** [comment] 2020-06-26 19:13
I'm confused - when I returned to the preview the result was indeed better. But then after resizing the text boxes and making a new preview, they have the same issue again.  

It does seem closely related to #2201 but slightly different

**Comment by bmattb** [comment] 2020-08-12 18:22
We should recheck this as there has been much work by @merapi around this, and it may no longer be valid.

**Comment by o-fernandez** [comment] 2020-08-19 14:21
Moving this to "Ready for Sprint" as I don't think this need product or UX specs.

**Comment by merapi** [comment] 2020-09-08 16:22
Will be tested/closed with #3530

**Comment by o-fernandez** [comment] 2020-09-10 17:07
I did some sanity checking, looks fine. I'm not the best at this, so may have missed things, but for now I'm OK with merging.

**Closed as completed** 2020-09-21 18:22 UTC
Labels: Type: Bug, P2, Elements: Text
